library(ggplot2)
library(vegan)


#rarefy raw data
I8S_rarefy_plot<-read.table("Cleaned.Zhanlulu.unoise3_TRANSPOSED.txt", header=T)
names(I8S_rarefy_plot)
I8S_OTU_rarefy<-I8S_rarefy_plot[2:7501]
S <- specnumber(I8S_OTU_rarefy) # observed number of species
(raremax <- min(rowSums(I8S_OTU_rarefy)))
Srare <- rarefy(I8S_OTU_rarefy, raremax)
plot(S, Srare, xlab = "Observed No. of Species", ylab = "Rarefied No. of Species")
abline(0, 1)
options(scipen=5)
rarecurve(I8S_OTU_rarefy, step = 50, cex = 0.6, label=TRUE)

COIrarefy_plot<-read.table("Cleaned.Leraylulu.unoise3_TRANSPOSED.txt", header=T)
names(COIrarefy_plot)
COI_OTU_rarefy<-COIrarefy_plot[2:17698]
S <- specnumber(COI_OTU_rarefy) # observed number of species
(raremax <- min(rowSums(COI_OTU_rarefy)))
Srare <- rarefy(COI_OTU_rarefy, raremax)
plot(S, Srare, xlab = "Observed No. of Species", ylab = "Rarefied No. of Species")
abline(0, 1)
options(scipen=5)
rarecurve(COI_OTU_rarefy, step = 50, cex = 0.6, label=TRUE)

#ASVs per supergroup boxplot
I8Sasv<-read.table("18S_pie_supergroup.txt", header=T)
attach(I8Sasv)
names(I8Sasv)

ggplot(data=I8Sasv, aes(fill=Supergroup, y=Numb, x=Supergroup)) +
  geom_bar(stat="identity") +
  theme(legend.position="right")+
  theme_classic()+
  labs( x = "Supergroup", y = "Number of Unique ASVs (18S)")

COIasv<-read.table("COI_pie_supergroup.txt", header=T)
attach(COIasv)
names(COIasv)

ggplot(data=COIasv, aes(fill=Supergroup, y=Numb, x=Supergroup)) +
  geom_bar(stat="identity") +
  theme(legend.position="right")+
  theme_classic()+
  labs( x = "Supergroup", y = "Number of ASVs (COI)")

otu_count<-read.table("eDNA_data_complete.txt", header=T)
otu_count
attach(otu_count)
names(otu_count)
hist(I8S_Shannon)
shapiro.test(I8S_otu_number)
shapiro.test(I8S_Evenness)
shapiro.test(I8S_Shannon)
shapiro.test(COI_otu_number)
shapiro.test(COI_Evenness)
shapiro.test(COI_Shannon)


#minimum adequate models - all non-significant

#18S ASV number
I8Sabiotic_otu_model<-lm(I8S_otu_number~human_impact*core_depth*PRT*CHO*LIP)
summary(I8Sabiotic_otu_model)
I8Sabiotic_otu_model2<-update(I8Sabiotic_otu_model,~.-human_impact:core_depth:PRT:CHO:LIP)
summary(I8Sabiotic_otu_model2)
anova(I8Sabiotic_otu_model,I8Sabiotic_otu_model2)
I8Sabiotic_otu_model3<-update(I8Sabiotic_otu_model2,~.-core_depth:PRT:CHO:LIP)
summary(I8Sabiotic_otu_model3)
anova(I8Sabiotic_otu_model2,I8Sabiotic_otu_model3)
I8Sabiotic_otu_model4<-update(I8Sabiotic_otu_model3,~.-human_impact:PRT:CHO:LIP)
summary(I8Sabiotic_otu_model4)
anova(I8Sabiotic_otu_model3,I8Sabiotic_otu_model4)
I8Sabiotic_otu_model5<-update(I8Sabiotic_otu_model4,~.-human_impact:core_depth:CHO:LIP)
summary(I8Sabiotic_otu_model5)
anova(I8Sabiotic_otu_model4,I8Sabiotic_otu_model5)
I8Sabiotic_otu_model6<-update(I8Sabiotic_otu_model5,~.-human_impact:core_depth:PRT:LI)
summary(I8Sabiotic_otu_model6)
anova(I8Sabiotic_otu_model5,I8Sabiotic_otu_model6)
I8Sabiotic_otu_model7<-update(I8Sabiotic_otu_model6,~.-human_impact:core_depth:PRT:LIP)
summary(I8Sabiotic_otu_model7)
anova(I8Sabiotic_otu_model5,I8Sabiotic_otu_model7)
I8Sabiotic_otu_model8<-update(I8Sabiotic_otu_model7,~.-human_impact:core_depth:PRT:CHO)
summary(I8Sabiotic_otu_model8)
anova(I8Sabiotic_otu_model7,I8Sabiotic_otu_model8)
I8Sabiotic_otu_model9<-update(I8Sabiotic_otu_model8,~.-PRT:CHO:LIP)
summary(I8Sabiotic_otu_model9)
anova(I8Sabiotic_otu_model8,I8Sabiotic_otu_model9)
I8Sabiotic_otu_model10<-update(I8Sabiotic_otu_model9,~.-core_depth:CHO:LIP)
summary(I8Sabiotic_otu_model10)
anova(I8Sabiotic_otu_model9,I8Sabiotic_otu_model10)
I8Sabiotic_otu_model11<-update(I8Sabiotic_otu_model10,~.-human_impact:CHO:LIP)
summary(I8Sabiotic_otu_model11)
anova(I8Sabiotic_otu_model10,I8Sabiotic_otu_model11)
I8Sabiotic_otu_model12<-update(I8Sabiotic_otu_model11,~.-core_depth:PRT:LIP)
summary(I8Sabiotic_otu_model12)
anova(I8Sabiotic_otu_model11,I8Sabiotic_otu_model12)
I8Sabiotic_otu_model13<-update(I8Sabiotic_otu_model12,~.-human_impact:PRT:LIP)
summary(I8Sabiotic_otu_model13)
anova(I8Sabiotic_otu_model12,I8Sabiotic_otu_model13)
I8Sabiotic_otu_model14<-update(I8Sabiotic_otu_model13,~.-human_impact:core_depth:LIP)
summary(I8Sabiotic_otu_model14)
anova(I8Sabiotic_otu_model13,I8Sabiotic_otu_model14)
I8Sabiotic_otu_model15<-update(I8Sabiotic_otu_model14,~.-core_depth:PRT:CHO)
summary(I8Sabiotic_otu_model15)
anova(I8Sabiotic_otu_model14,I8Sabiotic_otu_model15)
I8Sabiotic_otu_model16<-update(I8Sabiotic_otu_model15,~.-core_depth:PRT:CHO)
summary(I8Sabiotic_otu_model16)
anova(I8Sabiotic_otu_model15,I8Sabiotic_otu_model16)
I8Sabiotic_otu_model17<-update(I8Sabiotic_otu_model16,~.-human_impact:PRT:CHO)
summary(I8Sabiotic_otu_model17)
anova(I8Sabiotic_otu_model16,I8Sabiotic_otu_model17)
I8Sabiotic_otu_model18<-update(I8Sabiotic_otu_model17,~.-human_impact:core_depth:CHO)
summary(I8Sabiotic_otu_model18)
anova(I8Sabiotic_otu_model17,I8Sabiotic_otu_model18)
I8Sabiotic_otu_model19<-update(I8Sabiotic_otu_model18,~.-human_impact:core_depth:PRT)
summary(I8Sabiotic_otu_model19)
anova(I8Sabiotic_otu_model18,I8Sabiotic_otu_model19)
I8Sabiotic_otu_model20<-update(I8Sabiotic_otu_model19,~.-CHO:LIP)
summary(I8Sabiotic_otu_model20)
anova(I8Sabiotic_otu_model19,I8Sabiotic_otu_model20)
I8Sabiotic_otu_model21<-update(I8Sabiotic_otu_model20,~.-PRT:LIP)
summary(I8Sabiotic_otu_model21)
anova(I8Sabiotic_otu_model20,I8Sabiotic_otu_model21)
I8Sabiotic_otu_model22<-update(I8Sabiotic_otu_model21,~.-core_depth:LIP)
summary(I8Sabiotic_otu_model22)
anova(I8Sabiotic_otu_model21,I8Sabiotic_otu_model22)
I8Sabiotic_otu_model23<-update(I8Sabiotic_otu_model22,~.-core_depth:CHO)
summary(I8Sabiotic_otu_model23)
anova(I8Sabiotic_otu_model22,I8Sabiotic_otu_model23)
I8Sabiotic_otu_model24<-update(I8Sabiotic_otu_model23,~.-PRT:CHO)
summary(I8Sabiotic_otu_model24)
anova(I8Sabiotic_otu_model23,I8Sabiotic_otu_model24)
I8Sabiotic_otu_model25<-update(I8Sabiotic_otu_model24,~.-core_depth:PRT)
summary(I8Sabiotic_otu_model25)
anova(I8Sabiotic_otu_model24,I8Sabiotic_otu_model25)
I8Sabiotic_otu_model26<-update(I8Sabiotic_otu_model25,~.-human_impact:CHO)
summary(I8Sabiotic_otu_model26)
anova(I8Sabiotic_otu_model25,I8Sabiotic_otu_model26)
I8Sabiotic_otu_model27<-update(I8Sabiotic_otu_model26,~.-human_impact:core_depth)
summary(I8Sabiotic_otu_model27)
anova(I8Sabiotic_otu_model26,I8Sabiotic_otu_model27)
I8Sabiotic_otu_model28<-update(I8Sabiotic_otu_model27,~.-human_impact:LIP)
summary(I8Sabiotic_otu_model28)
anova(I8Sabiotic_otu_model27,I8Sabiotic_otu_model28)
I8Sabiotic_otu_model29<-update(I8Sabiotic_otu_model28,~.-human_impact:PRT)
summary(I8Sabiotic_otu_model29)
anova(I8Sabiotic_otu_model28,I8Sabiotic_otu_model29)
I8Sabiotic_otu_model30<-update(I8Sabiotic_otu_model29,~.-LIP)
summary(I8Sabiotic_otu_model30)
anova(I8Sabiotic_otu_model29,I8Sabiotic_otu_model30)
I8Sabiotic_otu_model31<-update(I8Sabiotic_otu_model30,~.-CHO)
summary(I8Sabiotic_otu_model31)
anova(I8Sabiotic_otu_model30,I8Sabiotic_otu_model31)
I8Sabiotic_otu_model32<-update(I8Sabiotic_otu_model31,~.-PRT)
summary(I8Sabiotic_otu_model32)
anova(I8Sabiotic_otu_model31,I8Sabiotic_otu_model32)
I8Sabiotic_otu_model33<-update(I8Sabiotic_otu_model32,~.-core_depth)
summary(I8Sabiotic_otu_model33)
anova(I8Sabiotic_otu_model32,I8Sabiotic_otu_model33)


#18S Shannon diversity scores
I8Sabiotic_shannon_model<-lm(I8S_Shannon~human_impact*core_depth*PRT*CHO*LIP*BPC)
summary(I8Sabiotic_shannon_model)
I8Sabiotic_shannon_model2<-update(I8Sabiotic_shannon_model,~.-human_impact:core_depth:PRT:CHO:LIP:BPC)
summary(I8Sabiotic_shannon_model2)
anova(I8Sabiotic_shannon_model,I8Sabiotic_shannon_model2)
I8Sabiotic_shannon_model3<-update(I8Sabiotic_shannon_model2,~.-core_depth:PRT:CHO:LIP:BPC)
summary(I8Sabiotic_shannon_model3)
anova(I8Sabiotic_shannon_model2,I8Sabiotic_shannon_model3)
I8Sabiotic_shannon_model4<-update(I8Sabiotic_shannon_model3,~.-human_impact:PRT:CHO:LIP:BPC)
summary(I8Sabiotic_shannon_model4)
anova(I8Sabiotic_shannon_model3,I8Sabiotic_shannon_model4)
I8Sabiotic_shannon_model5<-update(I8Sabiotic_shannon_model4,~.-human_impact:core_depth:CHO:LIP)
summary(I8Sabiotic_shannon_model5)
anova(I8Sabiotic_shannon_model4,I8Sabiotic_shannon_model5)
I8Sabiotic_shannon_model6<-update(I8Sabiotic_shannon_model5,~.-human_impact:core_depth:CHO:LIP:BPC)
summary(I8Sabiotic_shannon_model6)
anova(I8Sabiotic_shannon_model5,I8Sabiotic_shannon_model6)
I8Sabiotic_shannon_model7<-update(I8Sabiotic_shannon_model6,~.-human_impact:core_depth:PRT:LIP:BPC)
summary(I8Sabiotic_shannon_model7)
anova(I8Sabiotic_shannon_model5,I8Sabiotic_shannon_model7)
I8Sabiotic_shannon_model8<-update(I8Sabiotic_shannon_model7,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(I8Sabiotic_shannon_model8)
anova(I8Sabiotic_shannon_model7,I8Sabiotic_shannon_model8)
I8Sabiotic_shannon_model9<-update(I8Sabiotic_shannon_model8,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(I8Sabiotic_shannon_model9)
anova(I8Sabiotic_shannon_model8,I8Sabiotic_shannon_model9)
I8Sabiotic_shannon_model10<-update(I8Sabiotic_shannon_model9,~.-human_impact:core_depth:PRT:CHO:LIP)
summary(I8Sabiotic_shannon_model10)
anova(I8Sabiotic_shannon_model9,I8Sabiotic_shannon_model10)
I8Sabiotic_shannon_model11<-update(I8Sabiotic_shannon_model10,~.-PRT:CHO:LIP:BPC)
summary(I8Sabiotic_shannon_model11)
anova(I8Sabiotic_shannon_model10,I8Sabiotic_shannon_model11)
I8Sabiotic_shannon_model12<-update(I8Sabiotic_shannon_model11,~.-core_depth:CHO:LIP:BPC)
summary(I8Sabiotic_shannon_model12)
anova(I8Sabiotic_shannon_model11,I8Sabiotic_shannon_model12)
I8Sabiotic_shannon_model13<-update(I8Sabiotic_shannon_model12,~.-human_impact:CHO:LIP:BPC)
summary(I8Sabiotic_shannon_model13)
anova(I8Sabiotic_shannon_model12,I8Sabiotic_shannon_model13)
I8Sabiotic_shannon_model14<-update(I8Sabiotic_shannon_model13,~.-core_depth:PRT:LIP:BPC)
summary(I8Sabiotic_shannon_model14)
anova(I8Sabiotic_shannon_model13,I8Sabiotic_shannon_model14)
I8Sabiotic_shannon_model15<-update(I8Sabiotic_shannon_model14,~.-human_impact:PRT:LIP:BPC)
summary(I8Sabiotic_shannon_model15)
anova(I8Sabiotic_shannon_model14,I8Sabiotic_shannon_model15)
I8Sabiotic_shannon_model16<-update(I8Sabiotic_shannon_model15,~.-human_impact:core_depth:LIP:BPC)
summary(I8Sabiotic_shannon_model16)
anova(I8Sabiotic_shannon_model15,I8Sabiotic_shannon_model16)
I8Sabiotic_shannon_model17<-update(I8Sabiotic_shannon_model16,~.-core_depth:PRT:CHO:BPC)
summary(I8Sabiotic_shannon_model17)
anova(I8Sabiotic_shannon_model16,I8Sabiotic_shannon_model17)
I8Sabiotic_shannon_model18<-update(I8Sabiotic_shannon_model17,~.-human_impact:PRT:CHO:BPC)
summary(I8Sabiotic_shannon_model18)
anova(I8Sabiotic_shannon_model17,I8Sabiotic_shannon_model18)
I8Sabiotic_shannon_model19<-update(I8Sabiotic_shannon_model18,~.-human_impact:core_depth:CHO:BPC)
summary(I8Sabiotic_shannon_model19)
anova(I8Sabiotic_shannon_model18,I8Sabiotic_shannon_model19)
I8Sabiotic_shannon_model20<-update(I8Sabiotic_shannon_model19,~.-human_impact:core_depth:PRT:BPC)
summary(I8Sabiotic_shannon_model20)
anova(I8Sabiotic_shannon_model19,I8Sabiotic_shannon_model20)
I8Sabiotic_shannon_model21<-update(I8Sabiotic_shannon_model20,~.-core_depth:PRT:CHO:LIP)
summary(I8Sabiotic_shannon_model21)
anova(I8Sabiotic_shannon_model20,I8Sabiotic_shannon_model21)
I8Sabiotic_shannon_model22<-update(I8Sabiotic_shannon_model21,~.-human_impact:PRT:CHO:LIP)
summary(I8Sabiotic_shannon_model22)
anova(I8Sabiotic_shannon_model21,I8Sabiotic_shannon_model22)
I8Sabiotic_shannon_model23<-update(I8Sabiotic_shannon_model22,~.-human_impact:core_depth:PRT:LIP)
summary(I8Sabiotic_shannon_model23)
anova(I8Sabiotic_shannon_model22,I8Sabiotic_shannon_model23)
I8Sabiotic_shannon_model24<-update(I8Sabiotic_shannon_model23,~.-human_impact:core_depth:PRT:CHO)
summary(I8Sabiotic_shannon_model24)
anova(I8Sabiotic_shannon_model23,I8Sabiotic_shannon_model24)
I8Sabiotic_shannon_model25<-update(I8Sabiotic_shannon_model24,~.-CHO:LIP:BPC)
summary(I8Sabiotic_shannon_model25)
anova(I8Sabiotic_shannon_model24,I8Sabiotic_shannon_model25)
I8Sabiotic_shannon_model26<-update(I8Sabiotic_shannon_model25,~.-PRT:LIP:BPC)
summary(I8Sabiotic_shannon_model26)
anova(I8Sabiotic_shannon_model25,I8Sabiotic_shannon_model26)
I8Sabiotic_shannon_model27<-update(I8Sabiotic_shannon_model26,~.-core_depth:LIP:BPC)
summary(I8Sabiotic_shannon_model27)
anova(I8Sabiotic_shannon_model26,I8Sabiotic_shannon_model27)
I8Sabiotic_shannon_model28<-update(I8Sabiotic_shannon_model27,~.-human_impact:LIP:BPC)
summary(I8Sabiotic_shannon_model28)
anova(I8Sabiotic_shannon_model27,I8Sabiotic_shannon_model28)
I8Sabiotic_shannon_model29<-update(I8Sabiotic_shannon_model28,~.-PRT:CHO:BPC)
summary(I8Sabiotic_shannon_model29)
anova(I8Sabiotic_shannon_model28,I8Sabiotic_shannon_model29)
I8Sabiotic_shannon_model30<-update(I8Sabiotic_shannon_model29,~.-core_depth:CHO:BPC)
summary(I8Sabiotic_shannon_model30)
anova(I8Sabiotic_shannon_model29,I8Sabiotic_shannon_model30)
I8Sabiotic_shannon_model31<-update(I8Sabiotic_shannon_model30,~.-human_impact:CHO:BPC)
summary(I8Sabiotic_shannon_model31)
anova(I8Sabiotic_shannon_model30,I8Sabiotic_shannon_model31)
I8Sabiotic_shannon_model32<-update(I8Sabiotic_shannon_model31,~.-core_depth:PRT:BPC)
summary(I8Sabiotic_shannon_model32)
anova(I8Sabiotic_shannon_model31,I8Sabiotic_shannon_model32)
I8Sabiotic_shannon_model33<-update(I8Sabiotic_shannon_model32,~.-human_impact:PRT:BPC)
summary(I8Sabiotic_shannon_model33)
anova(I8Sabiotic_shannon_model32,I8Sabiotic_shannon_model33)
I8Sabiotic_shannon_model34<-update(I8Sabiotic_shannon_model33,~.-human_impact:core_depth:BPC)
summary(I8Sabiotic_shannon_model34)
anova(I8Sabiotic_shannon_model33,I8Sabiotic_shannon_model34)
I8Sabiotic_shannon_model35<-update(I8Sabiotic_shannon_model34,~.-PRT:CHO:LIP)
summary(I8Sabiotic_shannon_model35)
anova(I8Sabiotic_shannon_model34,I8Sabiotic_shannon_model35)
I8Sabiotic_shannon_model36<-update(I8Sabiotic_shannon_model35,~.-core_depth:CHO:LIP)
summary(I8Sabiotic_shannon_model36)
anova(I8Sabiotic_shannon_model35,I8Sabiotic_shannon_model36)
I8Sabiotic_shannon_model37<-update(I8Sabiotic_shannon_model36,~.-human_impact:CHO:LIP)
summary(I8Sabiotic_shannon_model37)
anova(I8Sabiotic_shannon_model36,I8Sabiotic_shannon_model37)
I8Sabiotic_shannon_model38<-update(I8Sabiotic_shannon_model37,~.-core_depth:PRT:LIP)
summary(I8Sabiotic_shannon_model38)
anova(I8Sabiotic_shannon_model37,I8Sabiotic_shannon_model38)
I8Sabiotic_shannon_model39<-update(I8Sabiotic_shannon_model38,~.-human_impact:PRT:LIP)
summary(I8Sabiotic_shannon_model39)
anova(I8Sabiotic_shannon_model38,I8Sabiotic_shannon_model39)
I8Sabiotic_shannon_model40<-update(I8Sabiotic_shannon_model39,~.-human_impact:core_depth:LIP)
summary(I8Sabiotic_shannon_model40)
anova(I8Sabiotic_shannon_model39,I8Sabiotic_shannon_model40)
I8Sabiotic_shannon_model41<-update(I8Sabiotic_shannon_model40,~.-core_depth:PRT:CHO)
summary(I8Sabiotic_shannon_model41)
anova(I8Sabiotic_shannon_model40,I8Sabiotic_shannon_model41)
I8Sabiotic_shannon_model42<-update(I8Sabiotic_shannon_model41,~.-human_impact:PRT:CHO)
summary(I8Sabiotic_shannon_model42)
anova(I8Sabiotic_shannon_model41,I8Sabiotic_shannon_model42)
I8Sabiotic_shannon_model43<-update(I8Sabiotic_shannon_model42,~.-human_impact:core_depth:CHO)
summary(I8Sabiotic_shannon_model43)
anova(I8Sabiotic_shannon_model42,I8Sabiotic_shannon_model43)
I8Sabiotic_shannon_model44<-update(I8Sabiotic_shannon_model43,~.-human_impact:core_depth:PRT)
summary(I8Sabiotic_shannon_model44)
anova(I8Sabiotic_shannon_model43,I8Sabiotic_shannon_model44)
I8Sabiotic_shannon_model45<-update(I8Sabiotic_shannon_model44,~.-LIP:BPC)
summary(I8Sabiotic_shannon_model45)
anova(I8Sabiotic_shannon_model44,I8Sabiotic_shannon_model45)
I8Sabiotic_shannon_model46<-update(I8Sabiotic_shannon_model45,~.-CHO:BPC)
summary(I8Sabiotic_shannon_model46)
anova(I8Sabiotic_shannon_model45,I8Sabiotic_shannon_model46)
I8Sabiotic_shannon_model47<-update(I8Sabiotic_shannon_model46,~.-PRT:BPC)
summary(I8Sabiotic_shannon_model47)
anova(I8Sabiotic_shannon_model46,I8Sabiotic_shannon_model47)
I8Sabiotic_shannon_model48<-update(I8Sabiotic_shannon_model47,~.-core_depth:BPC)
summary(I8Sabiotic_shannon_model48)
anova(I8Sabiotic_shannon_model47,I8Sabiotic_shannon_model48)
I8Sabiotic_shannon_model49<-update(I8Sabiotic_shannon_model48,~.-human_impact:BPC)
summary(I8Sabiotic_shannon_model49)
anova(I8Sabiotic_shannon_model48,I8Sabiotic_shannon_model49)
I8Sabiotic_shannon_model50<-update(I8Sabiotic_shannon_model49,~.-CHO:LIP)
summary(I8Sabiotic_shannon_model50)
anova(I8Sabiotic_shannon_model49,I8Sabiotic_shannon_model50)
I8Sabiotic_shannon_model51<-update(I8Sabiotic_shannon_model50,~.-PRT:LIP)
summary(I8Sabiotic_shannon_model51)
anova(I8Sabiotic_shannon_model50,I8Sabiotic_shannon_model51)
I8Sabiotic_shannon_model52<-update(I8Sabiotic_shannon_model51,~.-core_depth:LIP)
summary(I8Sabiotic_shannon_model52)
anova(I8Sabiotic_shannon_model51,I8Sabiotic_shannon_model52)
I8Sabiotic_shannon_model53<-update(I8Sabiotic_shannon_model52,~.-human_impact:LIP)
summary(I8Sabiotic_shannon_model53)
anova(I8Sabiotic_shannon_model52,I8Sabiotic_shannon_model53)
I8Sabiotic_shannon_model54<-update(I8Sabiotic_shannon_model53,~.-PRT:CHO)
summary(I8Sabiotic_shannon_model54)
anova(I8Sabiotic_shannon_model53,I8Sabiotic_shannon_model54)
I8Sabiotic_shannon_model55<-update(I8Sabiotic_shannon_model54,~.-core_depth:CHO)
summary(I8Sabiotic_shannon_model55)
anova(I8Sabiotic_shannon_model54,I8Sabiotic_shannon_model55)
I8Sabiotic_shannon_model56<-update(I8Sabiotic_shannon_model55,~.-human_impact:CHO)
summary(I8Sabiotic_shannon_model56)
anova(I8Sabiotic_shannon_model55,I8Sabiotic_shannon_model56)
I8Sabiotic_shannon_model57<-update(I8Sabiotic_shannon_model56,~.-core_depth:PRT)
summary(I8Sabiotic_shannon_model57)
anova(I8Sabiotic_shannon_model56,I8Sabiotic_shannon_model57)
I8Sabiotic_shannon_model58<-update(I8Sabiotic_shannon_model57,~.-human_impact:PRT)
summary(I8Sabiotic_shannon_model58)
anova(I8Sabiotic_shannon_model57,I8Sabiotic_shannon_model58)
I8Sabiotic_shannon_model59<-update(I8Sabiotic_shannon_model58,~.-human_impact:core_depth)
summary(I8Sabiotic_shannon_model59)
anova(I8Sabiotic_shannon_model58,I8Sabiotic_shannon_model59)
I8Sabiotic_shannon_model60<-update(I8Sabiotic_shannon_model59,~.-BPC)
summary(I8Sabiotic_shannon_model60)
anova(I8Sabiotic_shannon_model59,I8Sabiotic_shannon_model60)
I8Sabiotic_shannon_model61<-update(I8Sabiotic_shannon_model60,~.-LIP)
summary(I8Sabiotic_shannon_model61)
anova(I8Sabiotic_shannon_model60,I8Sabiotic_shannon_model61)
I8Sabiotic_shannon_model62<-update(I8Sabiotic_shannon_model61,~.-PRT)
summary(I8Sabiotic_shannon_model62)
anova(I8Sabiotic_shannon_model61,I8Sabiotic_shannon_model62)
I8Sabiotic_shannon_model63<-update(I8Sabiotic_shannon_model62,~.-CHO)
summary(I8Sabiotic_shannon_model63)
anova(I8Sabiotic_shannon_model62,I8Sabiotic_shannon_model63)
I8Sabiotic_shannon_model64<-update(I8Sabiotic_shannon_model63,~.-core_depth)
summary(I8Sabiotic_shannon_model64)
anova(I8Sabiotic_shannon_model63,I8Sabiotic_shannon_model64)

#18S Evenness scores
I8Sabiotic_Evenness_model<-lm(I8S_Evenness~human_impact*core_depth*PRT*CHO*LIP*BPC)
summary(I8Sabiotic_Evenness_model)
I8Sabiotic_Evenness_model2<-update(I8Sabiotic_Evenness_model,~.-human_impact:core_depth:PRT:CHO:LIP:BPC)
summary(I8Sabiotic_Evenness_model2)
anova(I8Sabiotic_Evenness_model,I8Sabiotic_Evenness_model2)
I8Sabiotic_Evenness_model3<-update(I8Sabiotic_Evenness_model2,~.-core_depth:PRT:CHO:LIP:BPC)
summary(I8Sabiotic_Evenness_model3)
anova(I8Sabiotic_Evenness_model2,I8Sabiotic_Evenness_model3)
I8Sabiotic_Evenness_model4<-update(I8Sabiotic_Evenness_model3,~.-human_impact:PRT:CHO:LIP:BPC)
summary(I8Sabiotic_Evenness_model4)
anova(I8Sabiotic_Evenness_model3,I8Sabiotic_Evenness_model4)
I8Sabiotic_Evenness_model5<-update(I8Sabiotic_Evenness_model4,~.-human_impact:core_depth:CHO:LIP)
summary(I8Sabiotic_Evenness_model5)
anova(I8Sabiotic_Evenness_model4,I8Sabiotic_Evenness_model5)
I8Sabiotic_Evenness_model6<-update(I8Sabiotic_Evenness_model5,~.-human_impact:core_depth:CHO:LIP:BPC)
summary(I8Sabiotic_Evenness_model6)
anova(I8Sabiotic_Evenness_model5,I8Sabiotic_Evenness_model6)
I8Sabiotic_Evenness_model7<-update(I8Sabiotic_Evenness_model6,~.-human_impact:core_depth:PRT:LIP:BPC)
summary(I8Sabiotic_Evenness_model7)
anova(I8Sabiotic_Evenness_model5,I8Sabiotic_Evenness_model7)
I8Sabiotic_Evenness_model8<-update(I8Sabiotic_Evenness_model7,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(I8Sabiotic_Evenness_model8)
anova(I8Sabiotic_Evenness_model7,I8Sabiotic_Evenness_model8)
I8Sabiotic_Evenness_model9<-update(I8Sabiotic_Evenness_model8,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(I8Sabiotic_Evenness_model9)
anova(I8Sabiotic_Evenness_model8,I8Sabiotic_Evenness_model9)
I8Sabiotic_Evenness_model10<-update(I8Sabiotic_Evenness_model9,~.-human_impact:core_depth:PRT:CHO:LIP)
summary(I8Sabiotic_Evenness_model10)
anova(I8Sabiotic_Evenness_model9,I8Sabiotic_Evenness_model10)
I8Sabiotic_Evenness_model11<-update(I8Sabiotic_Evenness_model10,~.-PRT:CHO:LIP:BPC)
summary(I8Sabiotic_Evenness_model11)
anova(I8Sabiotic_Evenness_model10,I8Sabiotic_Evenness_model11)
I8Sabiotic_Evenness_model12<-update(I8Sabiotic_Evenness_model11,~.-core_depth:CHO:LIP:BPC)
summary(I8Sabiotic_Evenness_model12)
anova(I8Sabiotic_Evenness_model11,I8Sabiotic_Evenness_model12)
I8Sabiotic_Evenness_model13<-update(I8Sabiotic_Evenness_model12,~.-human_impact:CHO:LIP:BPC)
summary(I8Sabiotic_Evenness_model13)
anova(I8Sabiotic_Evenness_model12,I8Sabiotic_Evenness_model13)
I8Sabiotic_Evenness_model14<-update(I8Sabiotic_Evenness_model13,~.-core_depth:PRT:LIP:BPC)
summary(I8Sabiotic_Evenness_model14)
anova(I8Sabiotic_Evenness_model13,I8Sabiotic_Evenness_model14)
I8Sabiotic_Evenness_model15<-update(I8Sabiotic_Evenness_model14,~.-human_impact:PRT:LIP:BPC)
summary(I8Sabiotic_Evenness_model15)
anova(I8Sabiotic_Evenness_model14,I8Sabiotic_Evenness_model15)
I8Sabiotic_Evenness_model16<-update(I8Sabiotic_Evenness_model15,~.-human_impact:core_depth:LIP:BPC)
summary(I8Sabiotic_Evenness_model16)
anova(I8Sabiotic_Evenness_model15,I8Sabiotic_Evenness_model16)
I8Sabiotic_Evenness_model17<-update(I8Sabiotic_Evenness_model16,~.-core_depth:PRT:CHO:BPC)
summary(I8Sabiotic_Evenness_model17)
anova(I8Sabiotic_Evenness_model16,I8Sabiotic_Evenness_model17)
I8Sabiotic_Evenness_model18<-update(I8Sabiotic_Evenness_model17,~.-human_impact:PRT:CHO:BPC)
summary(I8Sabiotic_Evenness_model18)
anova(I8Sabiotic_Evenness_model17,I8Sabiotic_Evenness_model18)
I8Sabiotic_Evenness_model19<-update(I8Sabiotic_Evenness_model18,~.-human_impact:core_depth:CHO:BPC)
summary(I8Sabiotic_Evenness_model19)
anova(I8Sabiotic_Evenness_model18,I8Sabiotic_Evenness_model19)
I8Sabiotic_Evenness_model20<-update(I8Sabiotic_Evenness_model19,~.-human_impact:core_depth:PRT:BPC)
summary(I8Sabiotic_Evenness_model20)
anova(I8Sabiotic_Evenness_model19,I8Sabiotic_Evenness_model20)
I8Sabiotic_Evenness_model21<-update(I8Sabiotic_Evenness_model20,~.-core_depth:PRT:CHO:LIP)
summary(I8Sabiotic_Evenness_model21)
anova(I8Sabiotic_Evenness_model20,I8Sabiotic_Evenness_model21)
I8Sabiotic_Evenness_model22<-update(I8Sabiotic_Evenness_model21,~.-human_impact:PRT:CHO:LIP)
summary(I8Sabiotic_Evenness_model22)
anova(I8Sabiotic_Evenness_model21,I8Sabiotic_Evenness_model22)
I8Sabiotic_Evenness_model23<-update(I8Sabiotic_Evenness_model22,~.-human_impact:core_depth:PRT:LIP)
summary(I8Sabiotic_Evenness_model23)
anova(I8Sabiotic_Evenness_model22,I8Sabiotic_Evenness_model23)
I8Sabiotic_Evenness_model24<-update(I8Sabiotic_Evenness_model23,~.-human_impact:core_depth:PRT:CHO)
summary(I8Sabiotic_Evenness_model24)
anova(I8Sabiotic_Evenness_model23,I8Sabiotic_Evenness_model24)
I8Sabiotic_Evenness_model25<-update(I8Sabiotic_Evenness_model24,~.-CHO:LIP:BPC)
summary(I8Sabiotic_Evenness_model25)
anova(I8Sabiotic_Evenness_model24,I8Sabiotic_Evenness_model25)
I8Sabiotic_Evenness_model26<-update(I8Sabiotic_Evenness_model25,~.-PRT:LIP:BPC)
summary(I8Sabiotic_Evenness_model26)
anova(I8Sabiotic_Evenness_model25,I8Sabiotic_Evenness_model26)
I8Sabiotic_Evenness_model27<-update(I8Sabiotic_Evenness_model26,~.-core_depth:LIP:BPC)
summary(I8Sabiotic_Evenness_model27)
anova(I8Sabiotic_Evenness_model26,I8Sabiotic_Evenness_model27)
I8Sabiotic_Evenness_model28<-update(I8Sabiotic_Evenness_model27,~.-human_impact:LIP:BPC)
summary(I8Sabiotic_Evenness_model28)
anova(I8Sabiotic_Evenness_model27,I8Sabiotic_Evenness_model28)
I8Sabiotic_Evenness_model29<-update(I8Sabiotic_Evenness_model28,~.-PRT:CHO:BPC)
summary(I8Sabiotic_Evenness_model29)
anova(I8Sabiotic_Evenness_model28,I8Sabiotic_Evenness_model29)
I8Sabiotic_Evenness_model30<-update(I8Sabiotic_Evenness_model29,~.-core_depth:CHO:BPC)
summary(I8Sabiotic_Evenness_model30)
anova(I8Sabiotic_Evenness_model29,I8Sabiotic_Evenness_model30)
I8Sabiotic_Evenness_model31<-update(I8Sabiotic_Evenness_model30,~.-human_impact:CHO:BPC)
summary(I8Sabiotic_Evenness_model31)
anova(I8Sabiotic_Evenness_model30,I8Sabiotic_Evenness_model31)
I8Sabiotic_Evenness_model32<-update(I8Sabiotic_Evenness_model31,~.-core_depth:PRT:BPC)
summary(I8Sabiotic_Evenness_model32)
anova(I8Sabiotic_Evenness_model31,I8Sabiotic_Evenness_model32)
I8Sabiotic_Evenness_model33<-update(I8Sabiotic_Evenness_model32,~.-human_impact:PRT:BPC)
summary(I8Sabiotic_Evenness_model33)
anova(I8Sabiotic_Evenness_model32,I8Sabiotic_Evenness_model33)
I8Sabiotic_Evenness_model34<-update(I8Sabiotic_Evenness_model33,~.-human_impact:core_depth:BPC)
summary(I8Sabiotic_Evenness_model34)
anova(I8Sabiotic_Evenness_model33,I8Sabiotic_Evenness_model34)
I8Sabiotic_Evenness_model35<-update(I8Sabiotic_Evenness_model34,~.-PRT:CHO:LIP)
summary(I8Sabiotic_Evenness_model35)
anova(I8Sabiotic_Evenness_model34,I8Sabiotic_Evenness_model35)
I8Sabiotic_Evenness_model36<-update(I8Sabiotic_Evenness_model35,~.-core_depth:CHO:LIP)
summary(I8Sabiotic_Evenness_model36)
anova(I8Sabiotic_Evenness_model35,I8Sabiotic_Evenness_model36)
I8Sabiotic_Evenness_model37<-update(I8Sabiotic_Evenness_model36,~.-human_impact:CHO:LIP)
summary(I8Sabiotic_Evenness_model37)
anova(I8Sabiotic_Evenness_model36,I8Sabiotic_Evenness_model37)
I8Sabiotic_Evenness_model38<-update(I8Sabiotic_Evenness_model37,~.-core_depth:PRT:LIP)
summary(I8Sabiotic_Evenness_model38)
anova(I8Sabiotic_Evenness_model37,I8Sabiotic_Evenness_model38)
I8Sabiotic_Evenness_model39<-update(I8Sabiotic_Evenness_model38,~.-human_impact:PRT:LIP)
summary(I8Sabiotic_Evenness_model39)
anova(I8Sabiotic_Evenness_model38,I8Sabiotic_Evenness_model39)
I8Sabiotic_Evenness_model40<-update(I8Sabiotic_Evenness_model39,~.-human_impact:core_depth:LIP)
summary(I8Sabiotic_Evenness_model40)
anova(I8Sabiotic_Evenness_model39,I8Sabiotic_Evenness_model40)
I8Sabiotic_Evenness_model41<-update(I8Sabiotic_Evenness_model40,~.-core_depth:PRT:CHO)
summary(I8Sabiotic_Evenness_model41)
anova(I8Sabiotic_Evenness_model40,I8Sabiotic_Evenness_model41)
I8Sabiotic_Evenness_model42<-update(I8Sabiotic_Evenness_model41,~.-human_impact:PRT:CHO)
summary(I8Sabiotic_Evenness_model42)
anova(I8Sabiotic_Evenness_model41,I8Sabiotic_Evenness_model42)
I8Sabiotic_Evenness_model43<-update(I8Sabiotic_Evenness_model42,~.-human_impact:core_depth:CHO)
summary(I8Sabiotic_Evenness_model43)
anova(I8Sabiotic_Evenness_model42,I8Sabiotic_Evenness_model43)
I8Sabiotic_Evenness_model44<-update(I8Sabiotic_Evenness_model43,~.-human_impact:core_depth:PRT)
summary(I8Sabiotic_Evenness_model44)
anova(I8Sabiotic_Evenness_model43,I8Sabiotic_Evenness_model44)
I8Sabiotic_Evenness_model45<-update(I8Sabiotic_Evenness_model44,~.-LIP:BPC)
summary(I8Sabiotic_Evenness_model45)
anova(I8Sabiotic_Evenness_model44,I8Sabiotic_Evenness_model45)
I8Sabiotic_Evenness_model46<-update(I8Sabiotic_Evenness_model45,~.-CHO:BPC)
summary(I8Sabiotic_Evenness_model46)
anova(I8Sabiotic_Evenness_model45,I8Sabiotic_Evenness_model46)
I8Sabiotic_Evenness_model47<-update(I8Sabiotic_Evenness_model46,~.-PRT:BPC)
summary(I8Sabiotic_Evenness_model47)
anova(I8Sabiotic_Evenness_model46,I8Sabiotic_Evenness_model47)
I8Sabiotic_Evenness_model48<-update(I8Sabiotic_Evenness_model47,~.-core_depth:BPC)
summary(I8Sabiotic_Evenness_model48)
anova(I8Sabiotic_Evenness_model47,I8Sabiotic_Evenness_model48)
I8Sabiotic_Evenness_model49<-update(I8Sabiotic_Evenness_model48,~.-human_impact:BPC)
summary(I8Sabiotic_Evenness_model49)
anova(I8Sabiotic_Evenness_model48,I8Sabiotic_Evenness_model49)
I8Sabiotic_Evenness_model50<-update(I8Sabiotic_Evenness_model49,~.-CHO:LIP)
summary(I8Sabiotic_Evenness_model50)
anova(I8Sabiotic_Evenness_model49,I8Sabiotic_Evenness_model50)
I8Sabiotic_Evenness_model51<-update(I8Sabiotic_Evenness_model50,~.-PRT:LIP)
summary(I8Sabiotic_Evenness_model51)
anova(I8Sabiotic_Evenness_model50,I8Sabiotic_Evenness_model51)
I8Sabiotic_Evenness_model52<-update(I8Sabiotic_Evenness_model51,~.-core_depth:LIP)
summary(I8Sabiotic_Evenness_model52)
anova(I8Sabiotic_Evenness_model51,I8Sabiotic_Evenness_model52)
I8Sabiotic_Evenness_model53<-update(I8Sabiotic_Evenness_model52,~.-human_impact:LIP)
summary(I8Sabiotic_Evenness_model53)
anova(I8Sabiotic_Evenness_model52,I8Sabiotic_Evenness_model53)
I8Sabiotic_Evenness_model54<-update(I8Sabiotic_Evenness_model53,~.-PRT:CHO)
summary(I8Sabiotic_Evenness_model54)
anova(I8Sabiotic_Evenness_model53,I8Sabiotic_Evenness_model54)
I8Sabiotic_Evenness_model55<-update(I8Sabiotic_Evenness_model54,~.-core_depth:CHO)
summary(I8Sabiotic_Evenness_model55)
anova(I8Sabiotic_Evenness_model54,I8Sabiotic_Evenness_model55)
I8Sabiotic_Evenness_model56<-update(I8Sabiotic_Evenness_model55,~.-human_impact:CHO)
summary(I8Sabiotic_Evenness_model56)
anova(I8Sabiotic_Evenness_model55,I8Sabiotic_Evenness_model56)
I8Sabiotic_Evenness_model57<-update(I8Sabiotic_Evenness_model56,~.-core_depth:PRT)
summary(I8Sabiotic_Evenness_model57)
anova(I8Sabiotic_Evenness_model56,I8Sabiotic_Evenness_model57)
I8Sabiotic_Evenness_model58<-update(I8Sabiotic_Evenness_model57,~.-human_impact:PRT)
summary(I8Sabiotic_Evenness_model58)
anova(I8Sabiotic_Evenness_model57,I8Sabiotic_Evenness_model58)
I8Sabiotic_Evenness_model59<-update(I8Sabiotic_Evenness_model58,~.-human_impact:core_depth)
summary(I8Sabiotic_Evenness_model59)
anova(I8Sabiotic_Evenness_model58,I8Sabiotic_Evenness_model59)
I8Sabiotic_Evenness_model60<-update(I8Sabiotic_Evenness_model59,~.-BPC)
summary(I8Sabiotic_Evenness_model60)
anova(I8Sabiotic_Evenness_model59,I8Sabiotic_Evenness_model60)
I8Sabiotic_Evenness_model61<-update(I8Sabiotic_Evenness_model60,~.-LIP)
summary(I8Sabiotic_Evenness_model61)
anova(I8Sabiotic_Evenness_model60,I8Sabiotic_Evenness_model61)
I8Sabiotic_Evenness_model62<-update(I8Sabiotic_Evenness_model61,~.-PRT)
summary(I8Sabiotic_Evenness_model62)
anova(I8Sabiotic_Evenness_model61,I8Sabiotic_Evenness_model62)
I8Sabiotic_Evenness_model63<-update(I8Sabiotic_Evenness_model62,~.-CHO)
summary(I8Sabiotic_Evenness_model63)
anova(I8Sabiotic_Evenness_model62,I8Sabiotic_Evenness_model63)
I8Sabiotic_Evenness_model64<-update(I8Sabiotic_Evenness_model63,~.-core_depth)
summary(I8Sabiotic_Evenness_model64)
anova(I8Sabiotic_Evenness_model63,I8Sabiotic_Evenness_model64)









#COI ASV number
COIabiotic_otu_number_model<-lm(COI_otu_number~human_impact*core_depth*PRT*CHO*LIP*BPC)
summary(COIabiotic_otu_number_model)
COIabiotic_otu_number_model2<-update(COIabiotic_otu_number_model,~.-human_impact:core_depth:PRT:CHO:LIP:BPC)
summary(COIabiotic_otu_number_model2)
anova(COIabiotic_otu_number_model,COIabiotic_otu_number_model2)
COIabiotic_otu_number_model3<-update(COIabiotic_otu_number_model2,~.-core_depth:PRT:CHO:LIP:BPC)
summary(COIabiotic_otu_number_model3)
anova(COIabiotic_otu_number_model2,COIabiotic_otu_number_model3)
COIabiotic_otu_number_model4<-update(COIabiotic_otu_number_model3,~.-human_impact:PRT:CHO:LIP:BPC)
summary(COIabiotic_otu_number_model4)
anova(COIabiotic_otu_number_model3,COIabiotic_otu_number_model4)
COIabiotic_otu_number_model5<-update(COIabiotic_otu_number_model4,~.-human_impact:core_depth:CHO:LIP)
summary(COIabiotic_otu_number_model5)
anova(COIabiotic_otu_number_model4,COIabiotic_otu_number_model5)
COIabiotic_otu_number_model6<-update(COIabiotic_otu_number_model5,~.-human_impact:core_depth:CHO:LIP:BPC)
summary(COIabiotic_otu_number_model6)
anova(COIabiotic_otu_number_model5,COIabiotic_otu_number_model6)
COIabiotic_otu_number_model7<-update(COIabiotic_otu_number_model6,~.-human_impact:core_depth:PRT:LIP:BPC)
summary(COIabiotic_otu_number_model7)
anova(COIabiotic_otu_number_model5,COIabiotic_otu_number_model7)
COIabiotic_otu_number_model8<-update(COIabiotic_otu_number_model7,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(COIabiotic_otu_number_model8)
anova(COIabiotic_otu_number_model7,COIabiotic_otu_number_model8)
COIabiotic_otu_number_model9<-update(COIabiotic_otu_number_model8,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(COIabiotic_otu_number_model9)
anova(COIabiotic_otu_number_model8,COIabiotic_otu_number_model9)
COIabiotic_otu_number_model10<-update(COIabiotic_otu_number_model9,~.-human_impact:core_depth:PRT:CHO:LIP)
summary(COIabiotic_otu_number_model10)
anova(COIabiotic_otu_number_model9,COIabiotic_otu_number_model10)
COIabiotic_otu_number_model11<-update(COIabiotic_otu_number_model10,~.-PRT:CHO:LIP:BPC)
summary(COIabiotic_otu_number_model11)
anova(COIabiotic_otu_number_model10,COIabiotic_otu_number_model11)
COIabiotic_otu_number_model12<-update(COIabiotic_otu_number_model11,~.-core_depth:CHO:LIP:BPC)
summary(COIabiotic_otu_number_model12)
anova(COIabiotic_otu_number_model11,COIabiotic_otu_number_model12)
COIabiotic_otu_number_model13<-update(COIabiotic_otu_number_model12,~.-human_impact:CHO:LIP:BPC)
summary(COIabiotic_otu_number_model13)
anova(COIabiotic_otu_number_model12,COIabiotic_otu_number_model13)
COIabiotic_otu_number_model14<-update(COIabiotic_otu_number_model13,~.-core_depth:PRT:LIP:BPC)
summary(COIabiotic_otu_number_model14)
anova(COIabiotic_otu_number_model13,COIabiotic_otu_number_model14)
COIabiotic_otu_number_model15<-update(COIabiotic_otu_number_model14,~.-human_impact:PRT:LIP:BPC)
summary(COIabiotic_otu_number_model15)
anova(COIabiotic_otu_number_model14,COIabiotic_otu_number_model15)
COIabiotic_otu_number_model16<-update(COIabiotic_otu_number_model15,~.-human_impact:core_depth:LIP:BPC)
summary(COIabiotic_otu_number_model16)
anova(COIabiotic_otu_number_model15,COIabiotic_otu_number_model16)
COIabiotic_otu_number_model17<-update(COIabiotic_otu_number_model16,~.-core_depth:PRT:CHO:BPC)
summary(COIabiotic_otu_number_model17)
anova(COIabiotic_otu_number_model16,COIabiotic_otu_number_model17)
COIabiotic_otu_number_model18<-update(COIabiotic_otu_number_model17,~.-human_impact:PRT:CHO:BPC)
summary(COIabiotic_otu_number_model18)
anova(COIabiotic_otu_number_model17,COIabiotic_otu_number_model18)
COIabiotic_otu_number_model19<-update(COIabiotic_otu_number_model18,~.-human_impact:core_depth:CHO:BPC)
summary(COIabiotic_otu_number_model19)
anova(COIabiotic_otu_number_model18,COIabiotic_otu_number_model19)
COIabiotic_otu_number_model20<-update(COIabiotic_otu_number_model19,~.-human_impact:core_depth:PRT:BPC)
summary(COIabiotic_otu_number_model20)
anova(COIabiotic_otu_number_model19,COIabiotic_otu_number_model20)
COIabiotic_otu_number_model21<-update(COIabiotic_otu_number_model20,~.-core_depth:PRT:CHO:LIP)
summary(COIabiotic_otu_number_model21)
anova(COIabiotic_otu_number_model20,COIabiotic_otu_number_model21)
COIabiotic_otu_number_model22<-update(COIabiotic_otu_number_model21,~.-human_impact:PRT:CHO:LIP)
summary(COIabiotic_otu_number_model22)
anova(COIabiotic_otu_number_model21,COIabiotic_otu_number_model22)
COIabiotic_otu_number_model23<-update(COIabiotic_otu_number_model22,~.-human_impact:core_depth:PRT:LIP)
summary(COIabiotic_otu_number_model23)
anova(COIabiotic_otu_number_model22,COIabiotic_otu_number_model23)
COIabiotic_otu_number_model24<-update(COIabiotic_otu_number_model23,~.-human_impact:core_depth:PRT:CHO)
summary(COIabiotic_otu_number_model24)
anova(COIabiotic_otu_number_model23,COIabiotic_otu_number_model24)
COIabiotic_otu_number_model25<-update(COIabiotic_otu_number_model24,~.-CHO:LIP:BPC)
summary(COIabiotic_otu_number_model25)
anova(COIabiotic_otu_number_model24,COIabiotic_otu_number_model25)
COIabiotic_otu_number_model26<-update(COIabiotic_otu_number_model25,~.-PRT:LIP:BPC)
summary(COIabiotic_otu_number_model26)
anova(COIabiotic_otu_number_model25,COIabiotic_otu_number_model26)
COIabiotic_otu_number_model27<-update(COIabiotic_otu_number_model26,~.-core_depth:LIP:BPC)
summary(COIabiotic_otu_number_model27)
anova(COIabiotic_otu_number_model26,COIabiotic_otu_number_model27)
COIabiotic_otu_number_model28<-update(COIabiotic_otu_number_model27,~.-human_impact:LIP:BPC)
summary(COIabiotic_otu_number_model28)
anova(COIabiotic_otu_number_model27,COIabiotic_otu_number_model28)
COIabiotic_otu_number_model29<-update(COIabiotic_otu_number_model28,~.-PRT:CHO:BPC)
summary(COIabiotic_otu_number_model29)
anova(COIabiotic_otu_number_model28,COIabiotic_otu_number_model29)
COIabiotic_otu_number_model30<-update(COIabiotic_otu_number_model29,~.-core_depth:CHO:BPC)
summary(COIabiotic_otu_number_model30)
anova(COIabiotic_otu_number_model29,COIabiotic_otu_number_model30)
COIabiotic_otu_number_model31<-update(COIabiotic_otu_number_model30,~.-human_impact:CHO:BPC)
summary(COIabiotic_otu_number_model31)
anova(COIabiotic_otu_number_model30,COIabiotic_otu_number_model31)
COIabiotic_otu_number_model32<-update(COIabiotic_otu_number_model31,~.-core_depth:PRT:BPC)
summary(COIabiotic_otu_number_model32)
anova(COIabiotic_otu_number_model31,COIabiotic_otu_number_model32)
COIabiotic_otu_number_model33<-update(COIabiotic_otu_number_model32,~.-human_impact:PRT:BPC)
summary(COIabiotic_otu_number_model33)
anova(COIabiotic_otu_number_model32,COIabiotic_otu_number_model33)
COIabiotic_otu_number_model34<-update(COIabiotic_otu_number_model33,~.-human_impact:core_depth:BPC)
summary(COIabiotic_otu_number_model34)
anova(COIabiotic_otu_number_model33,COIabiotic_otu_number_model34)
COIabiotic_otu_number_model35<-update(COIabiotic_otu_number_model34,~.-PRT:CHO:LIP)
summary(COIabiotic_otu_number_model35)
anova(COIabiotic_otu_number_model34,COIabiotic_otu_number_model35)
COIabiotic_otu_number_model36<-update(COIabiotic_otu_number_model35,~.-core_depth:CHO:LIP)
summary(COIabiotic_otu_number_model36)
anova(COIabiotic_otu_number_model35,COIabiotic_otu_number_model36)
COIabiotic_otu_number_model37<-update(COIabiotic_otu_number_model36,~.-human_impact:CHO:LIP)
summary(COIabiotic_otu_number_model37)
anova(COIabiotic_otu_number_model36,COIabiotic_otu_number_model37)
COIabiotic_otu_number_model38<-update(COIabiotic_otu_number_model37,~.-core_depth:PRT:LIP)
summary(COIabiotic_otu_number_model38)
anova(COIabiotic_otu_number_model37,COIabiotic_otu_number_model38)
COIabiotic_otu_number_model39<-update(COIabiotic_otu_number_model38,~.-human_impact:PRT:LIP)
summary(COIabiotic_otu_number_model39)
anova(COIabiotic_otu_number_model38,COIabiotic_otu_number_model39)
COIabiotic_otu_number_model40<-update(COIabiotic_otu_number_model39,~.-human_impact:core_depth:LIP)
summary(COIabiotic_otu_number_model40)
anova(COIabiotic_otu_number_model39,COIabiotic_otu_number_model40)
COIabiotic_otu_number_model41<-update(COIabiotic_otu_number_model40,~.-core_depth:PRT:CHO)
summary(COIabiotic_otu_number_model41)
anova(COIabiotic_otu_number_model40,COIabiotic_otu_number_model41)
COIabiotic_otu_number_model42<-update(COIabiotic_otu_number_model41,~.-human_impact:PRT:CHO)
summary(COIabiotic_otu_number_model42)
anova(COIabiotic_otu_number_model41,COIabiotic_otu_number_model42)
COIabiotic_otu_number_model43<-update(COIabiotic_otu_number_model42,~.-human_impact:core_depth:CHO)
summary(COIabiotic_otu_number_model43)
anova(COIabiotic_otu_number_model42,COIabiotic_otu_number_model43)
COIabiotic_otu_number_model44<-update(COIabiotic_otu_number_model43,~.-human_impact:core_depth:PRT)
summary(COIabiotic_otu_number_model44)
anova(COIabiotic_otu_number_model43,COIabiotic_otu_number_model44)
COIabiotic_otu_number_model45<-update(COIabiotic_otu_number_model44,~.-LIP:BPC)
summary(COIabiotic_otu_number_model45)
anova(COIabiotic_otu_number_model44,COIabiotic_otu_number_model45)
COIabiotic_otu_number_model46<-update(COIabiotic_otu_number_model45,~.-CHO:BPC)
summary(COIabiotic_otu_number_model46)
anova(COIabiotic_otu_number_model45,COIabiotic_otu_number_model46)
COIabiotic_otu_number_model47<-update(COIabiotic_otu_number_model46,~.-PRT:BPC)
summary(COIabiotic_otu_number_model47)
anova(COIabiotic_otu_number_model46,COIabiotic_otu_number_model47)
COIabiotic_otu_number_model48<-update(COIabiotic_otu_number_model47,~.-core_depth:BPC)
summary(COIabiotic_otu_number_model48)
anova(COIabiotic_otu_number_model47,COIabiotic_otu_number_model48)
COIabiotic_otu_number_model49<-update(COIabiotic_otu_number_model48,~.-human_impact:BPC)
summary(COIabiotic_otu_number_model49)
anova(COIabiotic_otu_number_model48,COIabiotic_otu_number_model49)
COIabiotic_otu_number_model50<-update(COIabiotic_otu_number_model49,~.-CHO:LIP)
summary(COIabiotic_otu_number_model50)
anova(COIabiotic_otu_number_model49,COIabiotic_otu_number_model50)
COIabiotic_otu_number_model51<-update(COIabiotic_otu_number_model50,~.-PRT:LIP)
summary(COIabiotic_otu_number_model51)
anova(COIabiotic_otu_number_model50,COIabiotic_otu_number_model51)
COIabiotic_otu_number_model52<-update(COIabiotic_otu_number_model51,~.-core_depth:LIP)
summary(COIabiotic_otu_number_model52)
anova(COIabiotic_otu_number_model51,COIabiotic_otu_number_model52)
COIabiotic_otu_number_model53<-update(COIabiotic_otu_number_model52,~.-human_impact:LIP)
summary(COIabiotic_otu_number_model53)
anova(COIabiotic_otu_number_model52,COIabiotic_otu_number_model53)
COIabiotic_otu_number_model54<-update(COIabiotic_otu_number_model53,~.-PRT:CHO)
summary(COIabiotic_otu_number_model54)
anova(COIabiotic_otu_number_model53,COIabiotic_otu_number_model54)
COIabiotic_otu_number_model55<-update(COIabiotic_otu_number_model54,~.-core_depth:CHO)
summary(COIabiotic_otu_number_model55)
anova(COIabiotic_otu_number_model54,COIabiotic_otu_number_model55)
COIabiotic_otu_number_model56<-update(COIabiotic_otu_number_model55,~.-human_impact:CHO)
summary(COIabiotic_otu_number_model56)
anova(COIabiotic_otu_number_model55,COIabiotic_otu_number_model56)
COIabiotic_otu_number_model57<-update(COIabiotic_otu_number_model56,~.-core_depth:PRT)
summary(COIabiotic_otu_number_model57)
anova(COIabiotic_otu_number_model56,COIabiotic_otu_number_model57)
COIabiotic_otu_number_model58<-update(COIabiotic_otu_number_model57,~.-human_impact:PRT)
summary(COIabiotic_otu_number_model58)
anova(COIabiotic_otu_number_model57,COIabiotic_otu_number_model58)
COIabiotic_otu_number_model59<-update(COIabiotic_otu_number_model58,~.-human_impact:core_depth)
summary(COIabiotic_otu_number_model59)
anova(COIabiotic_otu_number_model58,COIabiotic_otu_number_model59)
COIabiotic_otu_number_model60<-update(COIabiotic_otu_number_model59,~.-BPC)
summary(COIabiotic_otu_number_model60)
anova(COIabiotic_otu_number_model59,COIabiotic_otu_number_model60)
COIabiotic_otu_number_model61<-update(COIabiotic_otu_number_model60,~.-LIP)
summary(COIabiotic_otu_number_model61)
anova(COIabiotic_otu_number_model60,COIabiotic_otu_number_model61)
COIabiotic_otu_number_model62<-update(COIabiotic_otu_number_model61,~.-PRT)
summary(COIabiotic_otu_number_model62)
anova(COIabiotic_otu_number_model61,COIabiotic_otu_number_model62)
COIabiotic_otu_number_model63<-update(COIabiotic_otu_number_model62,~.-CHO)
summary(COIabiotic_otu_number_model63)
anova(COIabiotic_otu_number_model62,COIabiotic_otu_number_model63)
COIabiotic_otu_number_model64<-update(COIabiotic_otu_number_model63,~.-core_depth)
summary(COIabiotic_otu_number_model64)
anova(COIabiotic_otu_number_model63,COIabiotic_otu_number_model64)

#COI Shannon diversity scores
COIabiotic_Shannon_model<-lm(COI_Shannon~human_impact*core_depth*PRT*CHO*LIP*BPC)
summary(COIabiotic_Shannon_model)
COIabiotic_Shannon_model2<-update(COIabiotic_Shannon_model,~.-human_impact:core_depth:PRT:CHO:LIP:BPC)
summary(COIabiotic_Shannon_model2)
anova(COIabiotic_Shannon_model,COIabiotic_Shannon_model2)
COIabiotic_Shannon_model3<-update(COIabiotic_Shannon_model2,~.-core_depth:PRT:CHO:LIP:BPC)
summary(COIabiotic_Shannon_model3)
anova(COIabiotic_Shannon_model2,COIabiotic_Shannon_model3)
COIabiotic_Shannon_model4<-update(COIabiotic_Shannon_model3,~.-human_impact:PRT:CHO:LIP:BPC)
summary(COIabiotic_Shannon_model4)
anova(COIabiotic_Shannon_model3,COIabiotic_Shannon_model4)
COIabiotic_Shannon_model5<-update(COIabiotic_Shannon_model4,~.-human_impact:core_depth:CHO:LIP)
summary(COIabiotic_Shannon_model5)
anova(COIabiotic_Shannon_model4,COIabiotic_Shannon_model5)
COIabiotic_Shannon_model6<-update(COIabiotic_Shannon_model5,~.-human_impact:core_depth:CHO:LIP:BPC)
summary(COIabiotic_Shannon_model6)
anova(COIabiotic_Shannon_model5,COIabiotic_Shannon_model6)
COIabiotic_Shannon_model7<-update(COIabiotic_Shannon_model6,~.-human_impact:core_depth:PRT:LIP:BPC)
summary(COIabiotic_Shannon_model7)
anova(COIabiotic_Shannon_model5,COIabiotic_Shannon_model7)
COIabiotic_Shannon_model8<-update(COIabiotic_Shannon_model7,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(COIabiotic_Shannon_model8)
anova(COIabiotic_Shannon_model7,COIabiotic_Shannon_model8)
COIabiotic_Shannon_model9<-update(COIabiotic_Shannon_model8,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(COIabiotic_Shannon_model9)
anova(COIabiotic_Shannon_model8,COIabiotic_Shannon_model9)
COIabiotic_Shannon_model10<-update(COIabiotic_Shannon_model9,~.-human_impact:core_depth:PRT:CHO:LIP)
summary(COIabiotic_Shannon_model10)
anova(COIabiotic_Shannon_model9,COIabiotic_Shannon_model10)
COIabiotic_Shannon_model11<-update(COIabiotic_Shannon_model10,~.-PRT:CHO:LIP:BPC)
summary(COIabiotic_Shannon_model11)
anova(COIabiotic_Shannon_model10,COIabiotic_Shannon_model11)
COIabiotic_Shannon_model12<-update(COIabiotic_Shannon_model11,~.-core_depth:CHO:LIP:BPC)
summary(COIabiotic_Shannon_model12)
anova(COIabiotic_Shannon_model11,COIabiotic_Shannon_model12)
COIabiotic_Shannon_model13<-update(COIabiotic_Shannon_model12,~.-human_impact:CHO:LIP:BPC)
summary(COIabiotic_Shannon_model13)
anova(COIabiotic_Shannon_model12,COIabiotic_Shannon_model13)
COIabiotic_Shannon_model14<-update(COIabiotic_Shannon_model13,~.-core_depth:PRT:LIP:BPC)
summary(COIabiotic_Shannon_model14)
anova(COIabiotic_Shannon_model13,COIabiotic_Shannon_model14)
COIabiotic_Shannon_model15<-update(COIabiotic_Shannon_model14,~.-human_impact:PRT:LIP:BPC)
summary(COIabiotic_Shannon_model15)
anova(COIabiotic_Shannon_model14,COIabiotic_Shannon_model15)
COIabiotic_Shannon_model16<-update(COIabiotic_Shannon_model15,~.-human_impact:core_depth:LIP:BPC)
summary(COIabiotic_Shannon_model16)
anova(COIabiotic_Shannon_model15,COIabiotic_Shannon_model16)
COIabiotic_Shannon_model17<-update(COIabiotic_Shannon_model16,~.-core_depth:PRT:CHO:BPC)
summary(COIabiotic_Shannon_model17)
anova(COIabiotic_Shannon_model16,COIabiotic_Shannon_model17)
COIabiotic_Shannon_model18<-update(COIabiotic_Shannon_model17,~.-human_impact:PRT:CHO:BPC)
summary(COIabiotic_Shannon_model18)
anova(COIabiotic_Shannon_model17,COIabiotic_Shannon_model18)
COIabiotic_Shannon_model19<-update(COIabiotic_Shannon_model18,~.-human_impact:core_depth:CHO:BPC)
summary(COIabiotic_Shannon_model19)
anova(COIabiotic_Shannon_model18,COIabiotic_Shannon_model19)
COIabiotic_Shannon_model20<-update(COIabiotic_Shannon_model19,~.-human_impact:core_depth:PRT:BPC)
summary(COIabiotic_Shannon_model20)
anova(COIabiotic_Shannon_model19,COIabiotic_Shannon_model20)
COIabiotic_Shannon_model21<-update(COIabiotic_Shannon_model20,~.-core_depth:PRT:CHO:LIP)
summary(COIabiotic_Shannon_model21)
anova(COIabiotic_Shannon_model20,COIabiotic_Shannon_model21)
COIabiotic_Shannon_model22<-update(COIabiotic_Shannon_model21,~.-human_impact:PRT:CHO:LIP)
summary(COIabiotic_Shannon_model22)
anova(COIabiotic_Shannon_model21,COIabiotic_Shannon_model22)
COIabiotic_Shannon_model23<-update(COIabiotic_Shannon_model22,~.-human_impact:core_depth:PRT:LIP)
summary(COIabiotic_Shannon_model23)
anova(COIabiotic_Shannon_model22,COIabiotic_Shannon_model23)
COIabiotic_Shannon_model24<-update(COIabiotic_Shannon_model23,~.-human_impact:core_depth:PRT:CHO)
summary(COIabiotic_Shannon_model24)
anova(COIabiotic_Shannon_model23,COIabiotic_Shannon_model24)
COIabiotic_Shannon_model25<-update(COIabiotic_Shannon_model24,~.-CHO:LIP:BPC)
summary(COIabiotic_Shannon_model25)
anova(COIabiotic_Shannon_model24,COIabiotic_Shannon_model25)
COIabiotic_Shannon_model26<-update(COIabiotic_Shannon_model25,~.-PRT:LIP:BPC)
summary(COIabiotic_Shannon_model26)
anova(COIabiotic_Shannon_model25,COIabiotic_Shannon_model26)
COIabiotic_Shannon_model27<-update(COIabiotic_Shannon_model26,~.-core_depth:LIP:BPC)
summary(COIabiotic_Shannon_model27)
anova(COIabiotic_Shannon_model26,COIabiotic_Shannon_model27)
COIabiotic_Shannon_model28<-update(COIabiotic_Shannon_model27,~.-human_impact:LIP:BPC)
summary(COIabiotic_Shannon_model28)
anova(COIabiotic_Shannon_model27,COIabiotic_Shannon_model28)
COIabiotic_Shannon_model29<-update(COIabiotic_Shannon_model28,~.-PRT:CHO:BPC)
summary(COIabiotic_Shannon_model29)
anova(COIabiotic_Shannon_model28,COIabiotic_Shannon_model29)
COIabiotic_Shannon_model30<-update(COIabiotic_Shannon_model29,~.-core_depth:CHO:BPC)
summary(COIabiotic_Shannon_model30)
anova(COIabiotic_Shannon_model29,COIabiotic_Shannon_model30)
COIabiotic_Shannon_model31<-update(COIabiotic_Shannon_model30,~.-human_impact:CHO:BPC)
summary(COIabiotic_Shannon_model31)
anova(COIabiotic_Shannon_model30,COIabiotic_Shannon_model31)
COIabiotic_Shannon_model32<-update(COIabiotic_Shannon_model31,~.-core_depth:PRT:BPC)
summary(COIabiotic_Shannon_model32)
anova(COIabiotic_Shannon_model31,COIabiotic_Shannon_model32)
COIabiotic_Shannon_model33<-update(COIabiotic_Shannon_model32,~.-human_impact:PRT:BPC)
summary(COIabiotic_Shannon_model33)
anova(COIabiotic_Shannon_model32,COIabiotic_Shannon_model33)
COIabiotic_Shannon_model34<-update(COIabiotic_Shannon_model33,~.-human_impact:core_depth:BPC)
summary(COIabiotic_Shannon_model34)
anova(COIabiotic_Shannon_model33,COIabiotic_Shannon_model34)
COIabiotic_Shannon_model35<-update(COIabiotic_Shannon_model34,~.-PRT:CHO:LIP)
summary(COIabiotic_Shannon_model35)
anova(COIabiotic_Shannon_model34,COIabiotic_Shannon_model35)
COIabiotic_Shannon_model36<-update(COIabiotic_Shannon_model35,~.-core_depth:CHO:LIP)
summary(COIabiotic_Shannon_model36)
anova(COIabiotic_Shannon_model35,COIabiotic_Shannon_model36)
COIabiotic_Shannon_model37<-update(COIabiotic_Shannon_model36,~.-human_impact:CHO:LIP)
summary(COIabiotic_Shannon_model37)
anova(COIabiotic_Shannon_model36,COIabiotic_Shannon_model37)
COIabiotic_Shannon_model38<-update(COIabiotic_Shannon_model37,~.-core_depth:PRT:LIP)
summary(COIabiotic_Shannon_model38)
anova(COIabiotic_Shannon_model37,COIabiotic_Shannon_model38)
COIabiotic_Shannon_model39<-update(COIabiotic_Shannon_model38,~.-human_impact:PRT:LIP)
summary(COIabiotic_Shannon_model39)
anova(COIabiotic_Shannon_model38,COIabiotic_Shannon_model39)
COIabiotic_Shannon_model40<-update(COIabiotic_Shannon_model39,~.-human_impact:core_depth:LIP)
summary(COIabiotic_Shannon_model40)
anova(COIabiotic_Shannon_model39,COIabiotic_Shannon_model40)
COIabiotic_Shannon_model41<-update(COIabiotic_Shannon_model40,~.-core_depth:PRT:CHO)
summary(COIabiotic_Shannon_model41)
anova(COIabiotic_Shannon_model40,COIabiotic_Shannon_model41)
COIabiotic_Shannon_model42<-update(COIabiotic_Shannon_model41,~.-human_impact:PRT:CHO)
summary(COIabiotic_Shannon_model42)
anova(COIabiotic_Shannon_model41,COIabiotic_Shannon_model42)
COIabiotic_Shannon_model43<-update(COIabiotic_Shannon_model42,~.-human_impact:core_depth:CHO)
summary(COIabiotic_Shannon_model43)
anova(COIabiotic_Shannon_model42,COIabiotic_Shannon_model43)
COIabiotic_Shannon_model44<-update(COIabiotic_Shannon_model43,~.-human_impact:core_depth:PRT)
summary(COIabiotic_Shannon_model44)
anova(COIabiotic_Shannon_model43,COIabiotic_Shannon_model44)
COIabiotic_Shannon_model45<-update(COIabiotic_Shannon_model44,~.-LIP:BPC)
summary(COIabiotic_Shannon_model45)
anova(COIabiotic_Shannon_model44,COIabiotic_Shannon_model45)
COIabiotic_Shannon_model46<-update(COIabiotic_Shannon_model45,~.-CHO:BPC)
summary(COIabiotic_Shannon_model46)
anova(COIabiotic_Shannon_model45,COIabiotic_Shannon_model46)
COIabiotic_Shannon_model47<-update(COIabiotic_Shannon_model46,~.-PRT:BPC)
summary(COIabiotic_Shannon_model47)
anova(COIabiotic_Shannon_model46,COIabiotic_Shannon_model47)
COIabiotic_Shannon_model48<-update(COIabiotic_Shannon_model47,~.-core_depth:BPC)
summary(COIabiotic_Shannon_model48)
anova(COIabiotic_Shannon_model47,COIabiotic_Shannon_model48)
COIabiotic_Shannon_model49<-update(COIabiotic_Shannon_model48,~.-human_impact:BPC)
summary(COIabiotic_Shannon_model49)
anova(COIabiotic_Shannon_model48,COIabiotic_Shannon_model49)
COIabiotic_Shannon_model50<-update(COIabiotic_Shannon_model49,~.-CHO:LIP)
summary(COIabiotic_Shannon_model50)
anova(COIabiotic_Shannon_model49,COIabiotic_Shannon_model50)
COIabiotic_Shannon_model51<-update(COIabiotic_Shannon_model50,~.-PRT:LIP)
summary(COIabiotic_Shannon_model51)
anova(COIabiotic_Shannon_model50,COIabiotic_Shannon_model51)
COIabiotic_Shannon_model52<-update(COIabiotic_Shannon_model51,~.-core_depth:LIP)
summary(COIabiotic_Shannon_model52)
anova(COIabiotic_Shannon_model51,COIabiotic_Shannon_model52)
COIabiotic_Shannon_model53<-update(COIabiotic_Shannon_model52,~.-human_impact:LIP)
summary(COIabiotic_Shannon_model53)
anova(COIabiotic_Shannon_model52,COIabiotic_Shannon_model53)
COIabiotic_Shannon_model54<-update(COIabiotic_Shannon_model53,~.-PRT:CHO)
summary(COIabiotic_Shannon_model54)
anova(COIabiotic_Shannon_model53,COIabiotic_Shannon_model54)
COIabiotic_Shannon_model55<-update(COIabiotic_Shannon_model54,~.-core_depth:CHO)
summary(COIabiotic_Shannon_model55)
anova(COIabiotic_Shannon_model54,COIabiotic_Shannon_model55)
COIabiotic_Shannon_model56<-update(COIabiotic_Shannon_model55,~.-human_impact:CHO)
summary(COIabiotic_Shannon_model56)
anova(COIabiotic_Shannon_model55,COIabiotic_Shannon_model56)
COIabiotic_Shannon_model57<-update(COIabiotic_Shannon_model56,~.-core_depth:PRT)
summary(COIabiotic_Shannon_model57)
anova(COIabiotic_Shannon_model56,COIabiotic_Shannon_model57)
COIabiotic_Shannon_model58<-update(COIabiotic_Shannon_model57,~.-human_impact:PRT)
summary(COIabiotic_Shannon_model58)
anova(COIabiotic_Shannon_model57,COIabiotic_Shannon_model58)
COIabiotic_Shannon_model59<-update(COIabiotic_Shannon_model58,~.-human_impact:core_depth)
summary(COIabiotic_Shannon_model59)
anova(COIabiotic_Shannon_model58,COIabiotic_Shannon_model59)
COIabiotic_Shannon_model60<-update(COIabiotic_Shannon_model59,~.-BPC)
summary(COIabiotic_Shannon_model60)
anova(COIabiotic_Shannon_model59,COIabiotic_Shannon_model60)
COIabiotic_Shannon_model61<-update(COIabiotic_Shannon_model60,~.-LIP)
summary(COIabiotic_Shannon_model61)
anova(COIabiotic_Shannon_model60,COIabiotic_Shannon_model61)
COIabiotic_Shannon_model62<-update(COIabiotic_Shannon_model61,~.-PRT)
summary(COIabiotic_Shannon_model62)
anova(COIabiotic_Shannon_model61,COIabiotic_Shannon_model62)
COIabiotic_Shannon_model63<-update(COIabiotic_Shannon_model62,~.-CHO)
summary(COIabiotic_Shannon_model63)
anova(COIabiotic_Shannon_model62,COIabiotic_Shannon_model63)
COIabiotic_Shannon_model64<-update(COIabiotic_Shannon_model63,~.-core_depth)
summary(COIabiotic_Shannon_model64)
anova(COIabiotic_Shannon_model63,COIabiotic_Shannon_model64)

#COI Evenness Scores
COIabiotic_Evenness_model<-lm(COI_Evenness~human_impact*core_depth*PRT*CHO*LIP*BPC)
summary(COIabiotic_Evenness_model)
COIabiotic_Evenness_model2<-update(COIabiotic_Evenness_model,~.-human_impact:core_depth:PRT:CHO:LIP:BPC)
summary(COIabiotic_Evenness_model2)
anova(COIabiotic_Evenness_model,COIabiotic_Evenness_model2)
COIabiotic_Evenness_model3<-update(COIabiotic_Evenness_model2,~.-core_depth:PRT:CHO:LIP:BPC)
summary(COIabiotic_Evenness_model3)
anova(COIabiotic_Evenness_model2,COIabiotic_Evenness_model3)
COIabiotic_Evenness_model4<-update(COIabiotic_Evenness_model3,~.-human_impact:PRT:CHO:LIP:BPC)
summary(COIabiotic_Evenness_model4)
anova(COIabiotic_Evenness_model3,COIabiotic_Evenness_model4)
COIabiotic_Evenness_model5<-update(COIabiotic_Evenness_model4,~.-human_impact:core_depth:CHO:LIP)
summary(COIabiotic_Evenness_model5)
anova(COIabiotic_Evenness_model4,COIabiotic_Evenness_model5)
COIabiotic_Evenness_model6<-update(COIabiotic_Evenness_model5,~.-human_impact:core_depth:CHO:LIP:BPC)
summary(COIabiotic_Evenness_model6)
anova(COIabiotic_Evenness_model5,COIabiotic_Evenness_model6)
COIabiotic_Evenness_model7<-update(COIabiotic_Evenness_model6,~.-human_impact:core_depth:PRT:LIP:BPC)
summary(COIabiotic_Evenness_model7)
anova(COIabiotic_Evenness_model5,COIabiotic_Evenness_model7)
COIabiotic_Evenness_model8<-update(COIabiotic_Evenness_model7,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(COIabiotic_Evenness_model8)
anova(COIabiotic_Evenness_model7,COIabiotic_Evenness_model8)
COIabiotic_Evenness_model9<-update(COIabiotic_Evenness_model8,~.-human_impact:core_depth:PRT:CHO:BPC)
summary(COIabiotic_Evenness_model9)
anova(COIabiotic_Evenness_model8,COIabiotic_Evenness_model9)
COIabiotic_Evenness_model10<-update(COIabiotic_Evenness_model9,~.-human_impact:core_depth:PRT:CHO:LIP)
summary(COIabiotic_Evenness_model10)
anova(COIabiotic_Evenness_model9,COIabiotic_Evenness_model10)
COIabiotic_Evenness_model11<-update(COIabiotic_Evenness_model10,~.-PRT:CHO:LIP:BPC)
summary(COIabiotic_Evenness_model11)
anova(COIabiotic_Evenness_model10,COIabiotic_Evenness_model11)
COIabiotic_Evenness_model12<-update(COIabiotic_Evenness_model11,~.-core_depth:CHO:LIP:BPC)
summary(COIabiotic_Evenness_model12)
anova(COIabiotic_Evenness_model11,COIabiotic_Evenness_model12)
COIabiotic_Evenness_model13<-update(COIabiotic_Evenness_model12,~.-human_impact:CHO:LIP:BPC)
summary(COIabiotic_Evenness_model13)
anova(COIabiotic_Evenness_model12,COIabiotic_Evenness_model13)
COIabiotic_Evenness_model14<-update(COIabiotic_Evenness_model13,~.-core_depth:PRT:LIP:BPC)
summary(COIabiotic_Evenness_model14)
anova(COIabiotic_Evenness_model13,COIabiotic_Evenness_model14)
COIabiotic_Evenness_model15<-update(COIabiotic_Evenness_model14,~.-human_impact:PRT:LIP:BPC)
summary(COIabiotic_Evenness_model15)
anova(COIabiotic_Evenness_model14,COIabiotic_Evenness_model15)
COIabiotic_Evenness_model16<-update(COIabiotic_Evenness_model15,~.-human_impact:core_depth:LIP:BPC)
summary(COIabiotic_Evenness_model16)
anova(COIabiotic_Evenness_model15,COIabiotic_Evenness_model16)
COIabiotic_Evenness_model17<-update(COIabiotic_Evenness_model16,~.-core_depth:PRT:CHO:BPC)
summary(COIabiotic_Evenness_model17)
anova(COIabiotic_Evenness_model16,COIabiotic_Evenness_model17)
COIabiotic_Evenness_model18<-update(COIabiotic_Evenness_model17,~.-human_impact:PRT:CHO:BPC)
summary(COIabiotic_Evenness_model18)
anova(COIabiotic_Evenness_model17,COIabiotic_Evenness_model18)
COIabiotic_Evenness_model19<-update(COIabiotic_Evenness_model18,~.-human_impact:core_depth:CHO:BPC)
summary(COIabiotic_Evenness_model19)
anova(COIabiotic_Evenness_model18,COIabiotic_Evenness_model19)
COIabiotic_Evenness_model20<-update(COIabiotic_Evenness_model19,~.-human_impact:core_depth:PRT:BPC)
summary(COIabiotic_Evenness_model20)
anova(COIabiotic_Evenness_model19,COIabiotic_Evenness_model20)
COIabiotic_Evenness_model21<-update(COIabiotic_Evenness_model20,~.-core_depth:PRT:CHO:LIP)
summary(COIabiotic_Evenness_model21)
anova(COIabiotic_Evenness_model20,COIabiotic_Evenness_model21)
COIabiotic_Evenness_model22<-update(COIabiotic_Evenness_model21,~.-human_impact:PRT:CHO:LIP)
summary(COIabiotic_Evenness_model22)
anova(COIabiotic_Evenness_model21,COIabiotic_Evenness_model22)
COIabiotic_Evenness_model23<-update(COIabiotic_Evenness_model22,~.-human_impact:core_depth:PRT:LIP)
summary(COIabiotic_Evenness_model23)
anova(COIabiotic_Evenness_model22,COIabiotic_Evenness_model23)
COIabiotic_Evenness_model24<-update(COIabiotic_Evenness_model23,~.-human_impact:core_depth:PRT:CHO)
summary(COIabiotic_Evenness_model24)
anova(COIabiotic_Evenness_model23,COIabiotic_Evenness_model24)
COIabiotic_Evenness_model25<-update(COIabiotic_Evenness_model24,~.-CHO:LIP:BPC)
summary(COIabiotic_Evenness_model25)
anova(COIabiotic_Evenness_model24,COIabiotic_Evenness_model25)
COIabiotic_Evenness_model26<-update(COIabiotic_Evenness_model25,~.-PRT:LIP:BPC)
summary(COIabiotic_Evenness_model26)
anova(COIabiotic_Evenness_model25,COIabiotic_Evenness_model26)
COIabiotic_Evenness_model27<-update(COIabiotic_Evenness_model26,~.-core_depth:LIP:BPC)
summary(COIabiotic_Evenness_model27)
anova(COIabiotic_Evenness_model26,COIabiotic_Evenness_model27)
COIabiotic_Evenness_model28<-update(COIabiotic_Evenness_model27,~.-human_impact:LIP:BPC)
summary(COIabiotic_Evenness_model28)
anova(COIabiotic_Evenness_model27,COIabiotic_Evenness_model28)
COIabiotic_Evenness_model29<-update(COIabiotic_Evenness_model28,~.-PRT:CHO:BPC)
summary(COIabiotic_Evenness_model29)
anova(COIabiotic_Evenness_model28,COIabiotic_Evenness_model29)
COIabiotic_Evenness_model30<-update(COIabiotic_Evenness_model29,~.-core_depth:CHO:BPC)
summary(COIabiotic_Evenness_model30)
anova(COIabiotic_Evenness_model29,COIabiotic_Evenness_model30)
COIabiotic_Evenness_model31<-update(COIabiotic_Evenness_model30,~.-human_impact:CHO:BPC)
summary(COIabiotic_Evenness_model31)
anova(COIabiotic_Evenness_model30,COIabiotic_Evenness_model31)
COIabiotic_Evenness_model32<-update(COIabiotic_Evenness_model31,~.-core_depth:PRT:BPC)
summary(COIabiotic_Evenness_model32)
anova(COIabiotic_Evenness_model31,COIabiotic_Evenness_model32)
COIabiotic_Evenness_model33<-update(COIabiotic_Evenness_model32,~.-human_impact:PRT:BPC)
summary(COIabiotic_Evenness_model33)
anova(COIabiotic_Evenness_model32,COIabiotic_Evenness_model33)
COIabiotic_Evenness_model34<-update(COIabiotic_Evenness_model33,~.-human_impact:core_depth:BPC)
summary(COIabiotic_Evenness_model34)
anova(COIabiotic_Evenness_model33,COIabiotic_Evenness_model34)
COIabiotic_Evenness_model35<-update(COIabiotic_Evenness_model34,~.-PRT:CHO:LIP)
summary(COIabiotic_Evenness_model35)
anova(COIabiotic_Evenness_model34,COIabiotic_Evenness_model35)
COIabiotic_Evenness_model36<-update(COIabiotic_Evenness_model35,~.-core_depth:CHO:LIP)
summary(COIabiotic_Evenness_model36)
anova(COIabiotic_Evenness_model35,COIabiotic_Evenness_model36)
COIabiotic_Evenness_model37<-update(COIabiotic_Evenness_model36,~.-human_impact:CHO:LIP)
summary(COIabiotic_Evenness_model37)
anova(COIabiotic_Evenness_model36,COIabiotic_Evenness_model37)
COIabiotic_Evenness_model38<-update(COIabiotic_Evenness_model37,~.-core_depth:PRT:LIP)
summary(COIabiotic_Evenness_model38)
anova(COIabiotic_Evenness_model37,COIabiotic_Evenness_model38)
COIabiotic_Evenness_model39<-update(COIabiotic_Evenness_model38,~.-human_impact:PRT:LIP)
summary(COIabiotic_Evenness_model39)
anova(COIabiotic_Evenness_model38,COIabiotic_Evenness_model39)
COIabiotic_Evenness_model40<-update(COIabiotic_Evenness_model39,~.-human_impact:core_depth:LIP)
summary(COIabiotic_Evenness_model40)
anova(COIabiotic_Evenness_model39,COIabiotic_Evenness_model40)
COIabiotic_Evenness_model41<-update(COIabiotic_Evenness_model40,~.-core_depth:PRT:CHO)
summary(COIabiotic_Evenness_model41)
anova(COIabiotic_Evenness_model40,COIabiotic_Evenness_model41)
COIabiotic_Evenness_model42<-update(COIabiotic_Evenness_model41,~.-human_impact:PRT:CHO)
summary(COIabiotic_Evenness_model42)
anova(COIabiotic_Evenness_model41,COIabiotic_Evenness_model42)
COIabiotic_Evenness_model43<-update(COIabiotic_Evenness_model42,~.-human_impact:core_depth:CHO)
summary(COIabiotic_Evenness_model43)
anova(COIabiotic_Evenness_model42,COIabiotic_Evenness_model43)
COIabiotic_Evenness_model44<-update(COIabiotic_Evenness_model43,~.-human_impact:core_depth:PRT)
summary(COIabiotic_Evenness_model44)
anova(COIabiotic_Evenness_model43,COIabiotic_Evenness_model44)
COIabiotic_Evenness_model45<-update(COIabiotic_Evenness_model44,~.-LIP:BPC)
summary(COIabiotic_Evenness_model45)
anova(COIabiotic_Evenness_model44,COIabiotic_Evenness_model45)
COIabiotic_Evenness_model46<-update(COIabiotic_Evenness_model45,~.-CHO:BPC)
summary(COIabiotic_Evenness_model46)
anova(COIabiotic_Evenness_model45,COIabiotic_Evenness_model46)
COIabiotic_Evenness_model47<-update(COIabiotic_Evenness_model46,~.-PRT:BPC)
summary(COIabiotic_Evenness_model47)
anova(COIabiotic_Evenness_model46,COIabiotic_Evenness_model47)
COIabiotic_Evenness_model48<-update(COIabiotic_Evenness_model47,~.-core_depth:BPC)
summary(COIabiotic_Evenness_model48)
anova(COIabiotic_Evenness_model47,COIabiotic_Evenness_model48)
COIabiotic_Evenness_model49<-update(COIabiotic_Evenness_model48,~.-human_impact:BPC)
summary(COIabiotic_Evenness_model49)
anova(COIabiotic_Evenness_model48,COIabiotic_Evenness_model49)
COIabiotic_Evenness_model50<-update(COIabiotic_Evenness_model49,~.-CHO:LIP)
summary(COIabiotic_Evenness_model50)
anova(COIabiotic_Evenness_model49,COIabiotic_Evenness_model50)
COIabiotic_Evenness_model51<-update(COIabiotic_Evenness_model50,~.-PRT:LIP)
summary(COIabiotic_Evenness_model51)
anova(COIabiotic_Evenness_model50,COIabiotic_Evenness_model51)
COIabiotic_Evenness_model52<-update(COIabiotic_Evenness_model51,~.-core_depth:LIP)
summary(COIabiotic_Evenness_model52)
anova(COIabiotic_Evenness_model51,COIabiotic_Evenness_model52)
COIabiotic_Evenness_model53<-update(COIabiotic_Evenness_model52,~.-human_impact:LIP)
summary(COIabiotic_Evenness_model53)
anova(COIabiotic_Evenness_model52,COIabiotic_Evenness_model53)
COIabiotic_Evenness_model54<-update(COIabiotic_Evenness_model53,~.-PRT:CHO)
summary(COIabiotic_Evenness_model54)
anova(COIabiotic_Evenness_model53,COIabiotic_Evenness_model54)
COIabiotic_Evenness_model55<-update(COIabiotic_Evenness_model54,~.-core_depth:CHO)
summary(COIabiotic_Evenness_model55)
anova(COIabiotic_Evenness_model54,COIabiotic_Evenness_model55)
COIabiotic_Evenness_model56<-update(COIabiotic_Evenness_model55,~.-human_impact:CHO)
summary(COIabiotic_Evenness_model56)
anova(COIabiotic_Evenness_model55,COIabiotic_Evenness_model56)
COIabiotic_Evenness_model57<-update(COIabiotic_Evenness_model56,~.-core_depth:PRT)
summary(COIabiotic_Evenness_model57)
anova(COIabiotic_Evenness_model56,COIabiotic_Evenness_model57)
COIabiotic_Evenness_model58<-update(COIabiotic_Evenness_model57,~.-human_impact:PRT)
summary(COIabiotic_Evenness_model58)
anova(COIabiotic_Evenness_model57,COIabiotic_Evenness_model58)
COIabiotic_Evenness_model59<-update(COIabiotic_Evenness_model58,~.-human_impact:core_depth)
summary(COIabiotic_Evenness_model59)
anova(COIabiotic_Evenness_model58,COIabiotic_Evenness_model59)
COIabiotic_Evenness_model60<-update(COIabiotic_Evenness_model59,~.-BPC)
summary(COIabiotic_Evenness_model60)
anova(COIabiotic_Evenness_model59,COIabiotic_Evenness_model60)
COIabiotic_Evenness_model61<-update(COIabiotic_Evenness_model60,~.-LIP)
summary(COIabiotic_Evenness_model61)
anova(COIabiotic_Evenness_model60,COIabiotic_Evenness_model61)
COIabiotic_Evenness_model62<-update(COIabiotic_Evenness_model61,~.-PRT)
summary(COIabiotic_Evenness_model62)
anova(COIabiotic_Evenness_model61,COIabiotic_Evenness_model62)
COIabiotic_Evenness_model63<-update(COIabiotic_Evenness_model62,~.-CHO)
summary(COIabiotic_Evenness_model63)
anova(COIabiotic_Evenness_model62,COIabiotic_Evenness_model63)
COIabiotic_Evenness_model64<-update(COIabiotic_Evenness_model63,~.-core_depth)
summary(COIabiotic_Evenness_model64)
anova(COIabiotic_Evenness_model63,COIabiotic_Evenness_model64)

#18S non-parametric tests
kruskal.test(I8S_otu_number~human_impact)
kruskal.test(I8S_otu_number~survey_site)

kruskal.test(I8S_Shannon~human_impact)
kruskal.test(I8S_Shannon~survey_site)

kruskal.test(I8S_Evenness~human_impact)
kruskal.test(I8S_Evenness~survey_site)

#COI non-parametric tests
kruskal.test(COI_otu_number~human_impact)
kruskal.test(COI_otu_number~survey_site)

kruskal.test(COI_Evenness~human_impact)
kruskal.test(COI_Evenness~survey_site)

kruskal.test(COI_Shannon~human_impact)
kruskal.test(COI_Shannon~survey_site)


Site<-factor(site, levels=site[order(survey_site)])



#PLOTS FOR MODELS
Impact <- factor(otu_count$survey_site, levels = c("castellammare_impacted", "castellammare_pristine","palermo_impacted", "palermo_pristine_arenella", "palermo_pristine_eleuterio"), labels = c("Castellammare Impacted", "Castellammare Pristine","palermo_impacted", "palermo_pristine_arenella", "palermo_pristine_eleuterio"))
Region <- factor(otu_count$canyon, levels = c("castellammare", "palermo"), labels = c("Castellammare", "Palermo"))
Survey <- factor(otu_count$survey_site, levels = c("castellammare_impacted", "castellammare_pristine","palermo_impacted","palermo_pristine_eleuterio", "palermo_pristine_arenella"), 
                 labels = c("CT", "CU", "PT", "PUE", "PUA"))
#COI boxplots
boxplot(COI_otu_number~Impact, xlab="Trawling Condition", ylab = "Number of ASVs", col= (c("cornsilk3", "darkolivegreen3")))

boxplot(COI_Shannon~Impact, xlab="Trawling Condition", ylab = "Shannon Diversity", col= (c("cornsilk3", "darkolivegreen3")))

boxplot(COI_Evenness~Impact, xlab="Trawling Condition", ylab = "Species Evenness", col= (c("cornsilk3", "darkolivegreen3")))

boxplot(COI_otu_number~Region, xlab = "Canyon System", ylab = "Number of ASVs",
        col = (c("cornflowerblue", "goldenrod3")))

boxplot(COI_Shannon~Region, xlab = "Canyon System", ylab = "Shannon Diversity",
        col = (c("cornflowerblue", "goldenrod3")))

boxplot(COI_Evenness~Region, xlab = "Canyon System", ylab = "Species Evenness",
        col = (c("cornflowerblue", "goldenrod3")))

boxplot(COI_otu_number~Survey, xlab = "Sampling Station", ylab = "Number of ASVs", 
        col = (c("cornflowerblue", "lightblue1", "red2", "darksalmon", "darksalmon")))

boxplot(COI_Shannon~Survey, xlab = "Sampling Station", ylab = "Shannon Diversity", 
        col = (c("cornflowerblue", "lightblue1", "red2", "darksalmon", "darksalmon")))

boxplot(COI_Evenness~Survey, xlab = "Sampling Station", ylab = "Species Evenness", 
        col = (c("cornflowerblue", "lightblue1", "red2", "darksalmon", "darksalmon")))

#18S boxplots
boxplot(I8S_otu_number~Impact, xlab="Trawling Condition", ylab = "Number of ASVs", col= (c("cornsilk3", "darkolivegreen3")))

boxplot(I8S_Shannon~Impact, xlab="Trawling Condition", ylab = "Shannon Diversity", col= (c("cornsilk3", "darkolivegreen3")))

boxplot(I8S_Evenness~Impact, xlab="Trawling Condition", ylab = "Species Evenness", col= (c("cornsilk3", "darkolivegreen3")))

boxplot(I8S_otu_number~Region, xlab = "Canyon System", ylab = "Number of ASVs",
        col = (c("cornflowerblue", "goldenrod3")))

boxplot(I8S_Shannon~Region, xlab = "Canyon System", ylab = "Shannon Diversity",
        col = (c("cornflowerblue", "goldenrod3")))

boxplot(I8S_Evenness~Region, xlab = "Canyon System", ylab = "Species Evenness",
        col = (c("cornflowerblue", "goldenrod3")))

boxplot(I8S_otu_number~Survey, xlab = "Sampling Station", ylab = "Number of ASVs", 
        col = (c("cornflowerblue", "lightblue1", "red2", "darksalmon", "darksalmon")))

boxplot(I8S_Shannon~Survey, xlab = "Sampling Station", ylab = "Shannon Diversity", 
        col = (c("cornflowerblue", "lightblue1", "red2", "darksalmon", "darksalmon")))

boxplot(I8S_Evenness~Survey, xlab = "Sampling Station", ylab = "Species Evenness", 
        col = (c("cornflowerblue", "lightblue1", "red2", "darksalmon", "darksalmon")))

#PERMANOVAS
#18S
RNA_perm<-read.table("18S_compiled_data_POOLED_adonis.txt", header=T)
attach(RNA_perm)
names(RNA_perm)

RNA_perm_env<-read.table("18S_compiled_data_POOLED_adonis_env.txt", header=T)
attach(RNA_perm_env)
names(RNA_perm_env)

adonis2(RNA_perm ~ human_impact*region, method = 'jaccard',data = RNA_perm_env)

dis <- vegdist(RNA_perm)
region <- factor(c(rep(1,2), rep(2,1),rep(3,1),rep(4,4),rep(5,6),rep(6,1)), labels = c("Palermo","Castellammare","Palermo","Castellammare","Palermo","Castellammare"))
impact<- factor(c(rep(1,2), rep(2,1),rep(3,1),rep(4,1),rep(5,2),rep(6,1),rep(7,2),rep(8,2),rep(9,1),rep(10,1),rep(11,1)), labels = c("Pristine", "Impacted","Pristine", "Impacted","Pristine", "Impacted","Pristine", "Impacted","Pristine", "Impacted","Pristine"))
regimp<- factor(c(rep(1,2), rep(2,1),rep(3,1),rep(4,1),rep(5,2),rep(6,1),rep(7,2),rep(8,2),rep(9,1),rep(10,1),rep(11,1)), labels = c("Pal_Pristine", "Cast_Impacted","Pal_Pristine", "Cast_Impacted","Cast_Pristine", "Cast_Impacted","Pal_Pristine", "Pal_Impacted","Pal_Pristine", "Pal_Impacted","Cast_Pristine"))


RNAregmod<-betadisper(dis,region)
RNAimpmod<-betadisper(dis,impact)
RNAregimp<-betadisper(dis,regimp)
anova(RNAregmod)
anova(RNAimpmod)
anova(RNAregimp)
plot(RNAregimp)

#COI
COI_perm<-read.table("COI_compiled_data_POOLED_adonis.txt", header=T)
attach(COI_perm)
names(COI_perm)

COI_perm_env<-read.table("COI_compiled_data_POOLED_adonis_env.txt", header=T)
attach(COI_perm_env)
names(COI_perm_env)

adonis2(COI_perm ~ human_impact*region, method = 'jaccard',data = COI_perm_env)

dis <- vegdist(COI_perm)
region <- factor(c(rep(1,2), rep(2,1),rep(3,1),rep(4,4),rep(5,6),rep(6,1)), labels = c("Palermo","Castellammare","Palermo","Castellammare","Palermo","Castellammare"))
impact<- factor(c(rep(1,2), rep(2,1),rep(3,1),rep(4,1),rep(5,2),rep(6,1),rep(7,2),rep(8,2),rep(9,1),rep(10,1),rep(11,1)), labels = c("Pristine", "Impacted","Pristine", "Impacted","Pristine", "Impacted","Pristine", "Impacted","Pristine", "Impacted","Pristine"))
regimp<- factor(c(rep(1,2), rep(2,1),rep(3,1),rep(4,1),rep(5,2),rep(6,1),rep(7,2),rep(8,2),rep(9,1),rep(10,1),rep(11,1)), labels = c("Pal_Pristine", "Cast_Impacted","Pal_Pristine", "Cast_Impacted","Cast_Pristine", "Cast_Impacted","Pal_Pristine", "Pal_Impacted","Pal_Pristine", "Pal_Impacted","Cast_Pristine"))

COIregmod<-betadisper(dis,region)
COIimpmod<-betadisper(dis,impact)
COIregimp<-betadisper(dis,regimp)
anova(COIregmod)
anova(COIimpmod)
anova(COIregimp)

boxplot(RNAregmod, label = FALSE)

#CORRELATIONS - all non-significant
#depth correlation
core_depth_model<-lm(otu_number~core_depth)
core_depth_model
summary(core_depth_model)
plot(otu_number~core_depth)
text(srt = 45)
cor.test(otu_number,core_depth, method="pearson")

#protein correlation
PRT_model<-lm(otu_number~PRT)
PRT_model
summary(PRT_model)
plot(otu_number~PRT)
cor.test(otu_number,PRT, method="pearson")
#carbohydrate correlation
CHO_model<-lm(otu_number~CHO)
cor.test(otu_number,CHO, method="pearson")
CHO_model
summary(CHO_model)
plot(otu_number~CHO, xlab="Carbohydrates", ylab = "OTU Number")
legend(0.42, 1200, legend=c("Impacted", "Pristine"),
       col=c("coral", "darkolivegreen3"),pch=c(19,19), ,lwd=0, cex=0.7)
points(otu_number[human_impact=="impacted"]~CHO[human_impact=="impacted"],col="coral",pch=19)
points(otu_number[human_impact=="pristine"]~CHO[human_impact=="pristine"],col="darkolivegreen3",pch=19)
abline(CHO_model)

#lipid correlation
cor.test(otu_number,LIP, method="pearson")
LIP_model<-lm(otu_number~LIP)
plot(otu_number~LIP, ylab = "OTU Number", xlab = "Lipids")
legend(0.42, 800, legend=c("Impacted", "Pristine"),
       col=c("coral", "darkolivegreen3"),pch=c(19,19), ,lwd=0, cex=0.7)
points(otu_number[human_impact=="impacted"]~LIP[human_impact=="impacted"],col="coral",pch=19)
points(otu_number[human_impact=="pristine"]~LIP[human_impact=="pristine"],col="darkolivegreen3",pch=19)
abline(LIP_model)

#BPC correlation
BPC_model<-lm(otu_number~BPC)
BPC_model
summary(BPC_model)
plot(otu_number~BPC)
cor.test(otu_number,BPC, method="pearson")

#phytopigment correlations
Phytopigment_Chl.a_model<-lm(otu_number~Phytopigment_Chl.a)
Phytopigment_Chl.a_model
summary(Phytopigment_Chl.a_model)
plot(otu_number~Phytopigment_Chl.a)

Phytopigment_C_model<-lm(otu_number~Phytopigment_C)
Phytopigment_C_model
summary(Phytopigment_C_model)
plot(otu_number~Phytopigment_C)

Phytopigment_BPC_model<-lm(otu_number~Phytopigment_BPC)
Phytopigment_BPC_model
summary(Phytopigment_BPC_model)
plot(otu_number~Phytopigment_BPC)


#18S MDS Plot
palette(c("lightblue1", "lightblue1", "red2", "darksalmon", "darksalmon"))
MDS_plot<-read.table("18S_compiled_data_POOLED.txt", header=T)
names(MDS_plot)
OTU_MDS<-MDS_plot[2:7502]
OTU_MDS.mds <- metaMDS(comm = OTU_MDS, k=3,distance = "jaccard", trace = FALSE, autotransform = FALSE)
plot(OTU_MDS.mds$points) 
MDS_xy <- data.frame(OTU_MDS.mds$points)
MDS_xy$ecorep <- MDS_plot$phylum
MDS_xy$Site <- MDS_plot$condition
MDS_xy$Region <- MDS_plot$region
MDS_xy$Condition <- MDS_plot$human_impact
sites<- MDS_plot$phylum
sites
plot(OTU_MDS.mds$points) 
plot(OTU_MDS.mds$points, col=c("light blue","red")[MDS_plot$region],pch=c(16,17)[as.integer(MDS_plot$human_impact)],main="",cex=2.5,xlab="",ylab="")
ordispider(OTU_MDS.mds,MDS_plot$condition,
           lty=1,
           lwd=2,
           col=c("light blue", 'light blue','red',"red"))
ordihull(OTU_MDS.mds,MDS_plot$condition,
         draw = "polygon",
         lty=0,
         col=c("light blue", 'light blue','red',"red"))
text(OTU_MDS.mds, labels = MDS_plot$phylum, adj = c(0.5,0.5))


OTU_MDS.mds$stress

points(OTU_MDS.mds$points)
points

#COI nMDS plot
MDS_plot<-read.table("COI_compiled_data_POOLED.txt", header=T)
names(MDS_plot)
OTU_MDS<-MDS_plot[2:17699]
OTU_MDS.mds <- metaMDS(comm = OTU_MDS, k=3,distance = "jaccard", trace = FALSE, autotransform = FALSE)
plot(OTU_MDS.mds$points) 
MDS_xy <- data.frame(OTU_MDS.mds$points)
MDS_xy$ecorep <- MDS_plot$phylum
MDS_xy$Condition <- MDS_plot$condition
MDS_xy$Region <- MDS_plot$region
MDS_xy$Impact <- MDS_plot$human_impact
plot(OTU_MDS.mds$points) 
plot(OTU_MDS.mds$points, col=c("light blue","red")[MDS_plot$region],pch=c(16,17)[as.integer(MDS_plot$human_impact)],main="",cex=2.5,xlab="",ylab="")
ordispider(OTU_MDS.mds,MDS_plot$condition,
           lty=1,
           lwd=2,
           col=c("light blue", 'light blue','red',"red"))
ordihull(OTU_MDS.mds,MDS_plot$condition,
         draw = "polygon",
         lty=0,
         col=c("light blue", 'light blue','red',"red"))
text(OTU_MDS.mds, labels = MDS_plot$phylum, adj = c(0.5,0.5))

q<-ggplot(MDS_xy, aes(MDS1, MDS2, color = Region, fill = Region, shape = Impact,size=3)) +
  geom_point() + geom_text(label = MDS_plot$phylum, nudge_x=-0.0, nudge_y = -0.06,color = "black")+ theme_classic()
q
q + scale_colour_manual(values = c("Castellammare" = "blue", "Palermo" = "red"))
OTU_MDS.mds$stress

#COI nMDS plot - CU3 replicate removed
MDS_plot<-read.table("COI_compiled_data_POOLED_noCU3.txt", header=T)
names(MDS_plot)
OTU_MDS<-MDS_plot[2:17699]
OTU_MDS.mds <- metaMDS(comm = OTU_MDS, k=3,distance = "jaccard", trace = FALSE, autotransform = FALSE)
plot(OTU_MDS.mds$points) 
MDS_xy <- data.frame(OTU_MDS.mds$points)
MDS_xy$ecorep <- MDS_plot$phylum
MDS_xy$Site <- MDS_plot$condition
MDS_xy$Region <- MDS_plot$region
MDS_xy$Condition <- MDS_plot$human_impact
q<-ggplot(MDS_xy, aes(MDS1, MDS2, color = Region, fill = Region, shape = Condition,size=3)) +
  geom_point() + geom_text(label = MDS_plot$phylum, nudge_x=-0.0, nudge_y = -0.06,color = "black")+ theme_classic()
q
q + scale_colour_manual(values = c("Castellammare" = "blue", "Palermo" = "red"))
OTU_MDS.mds$stress



#Metazoa taxonomy breakdown per site
RNAtax<-read.table("18S_stacked_bar_meta_assign.txt",header=TRUE)
RNAtax
names(RNAtax)
attach(RNAtax)

RNAcbPalette <- c("#56B4E9", "#0072B2", "#99FF66", "#009E73", "#FF9999", "#FF3300", "#FFCC66", "#E69F00","#CC66FF", "#330066", "#FFFF99", "#996633", "#99FFFF","#00CC99", "#666666", "#CCFF33", "#000000")

ggplot(RNAtax, aes(fill=Phylum, y=Unique_OTUs, x=Region)) + 
  geom_bar(stat="identity") + theme_classic()+
  scale_x_discrete(labels=c("CT", 
                            "CU", 
                            "PT", 
                            "PUA", 
                            "PUE"))+
  labs( x = "Sample Station", y = "Unique 18S ASVs (Square Root Transformed)")+
  scale_fill_manual(values=RNAcbPalette)


COItax<-read.table("COI_stacked_bar.txt",header=TRUE)
COItax
names(COItax)
attach(COItax)

COIcbPalette <- c("#56B4E9", "#0072B2", "#009E73", "#FF9999", "#FFCC66","#CC66FF", "#FFFF99", "#996633", "#99FFFF","#00CC99", "#CCFF33", "#CCCCCC")


ggplot(COItax, aes(fill=Phylum, y=Unique_OTUs, x=Region)) + 
  geom_bar(stat="identity") + theme_classic()+
  labs( x = "Sampling Station", y = "Unique COI ASVs (Square Root Transformed)")+
  scale_fill_manual(values=COIcbPalette)





